apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: auditd-dir-access
  annotations:
    policy.open-cluster-management.io/categories: OCPC - OpenShift Compliance
    policy.open-cluster-management.io/standards: Kemo Labs 2026
    policy.open-cluster-management.io/controls: CR - Compliance Remediation
    compliance.openshift.io/last-scanned-timestamp: 2026-07-07T03:00:05Z
    compliance.openshift.io/rule: directory-access-var-log-oauth-audit,directory-access-var-log-ocp-audit,directory-access-var-log-kube-audit
    control.compliance.openshift.io/NIST-800-53: AU-2(d);AU-12(c);AC-6(9);CM-6(a)
    control.compliance.openshift.io/PCI-DSS-4-0: 10.3.2;10.3
    control.compliance.openshift.io/SRG: SRG-APP-000343-CTR-000780
    policies.open-cluster-management.io/controls: AU-2(d),AU-12(c),AC-6(9),CM-6(a),SRG-APP-000343-CTR-000780,10.3.2,10.3
    policies.open-cluster-management.io/standards: NIST-800-53,SRG,PCI-DSS-4-0
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: auditd-dir-access
        spec:
          remediationAction: enforce
          severity: high
          pruneObjectBehavior: DeleteIfCreated
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: machineconfiguration.openshift.io/v1
                kind: MachineConfig
                metadata:
                  labels:
                    machineconfiguration.openshift.io/role: master
                  name: 75-master-auditd-dir-access
                spec:
                  config:
                    ignition:
                      version: 3.1.0
                    storage:
                      files:
                        - contents:
                            source: 'data:,-a%20always%2Cexit%20-F%20dir%3D%2Fvar%2Flog%2Fkube-apiserver%2F%20-F%20perm%3Dr%20-F%20auid%3E%3D1000%20-F%20auid!%3Dunset%20-F%20key%3Daccess-audit-trail'
                          mode: 420
                          overwrite: true
                          path: /etc/audit/rules.d/75-var-log-kube.rules
                        - contents:
                            source: 'data:,-a%20always%2Cexit%20-F%20dir%3D%2Fvar%2Flog%2Fopenshift-apiserver%2F%20-F%20perm%3Dr%20-F%20auid%3E%3D1000%20-F%20auid!%3Dunset%20-F%20key%3Daccess-audit-trail'
                          mode: 420
                          overwrite: true
                          path: /etc/audit/rules.d/75-var-log-ocp.rules
                        - contents:
                            source: 'data:,-a%20always%2Cexit%20-F%20dir%3D%2Fvar%2Flog%2Foauth-apiserver%2F%20-F%20perm%3Dr%20-F%20auid%3E%3D1000%20-F%20auid!%3Dunset%20-F%20key%3Daccess-audit-trail'
                          mode: 420
                          overwrite: true
                          path: /etc/audit/rules.d/75-var-log-oauth.rules
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: machineconfiguration.openshift.io/v1
                kind: MachineConfig
                metadata:
                  labels:
                    machineconfiguration.openshift.io/role: worker
                  name: 75-worker-auditd-dir-access
                spec:
                  config:
                    ignition:
                      version: 3.1.0
                    storage:
                      files:
                        - contents:
                            source: 'data:,-a%20always%2Cexit%20-F%20dir%3D%2Fvar%2Flog%2Fkube-apiserver%2F%20-F%20perm%3Dr%20-F%20auid%3E%3D1000%20-F%20auid!%3Dunset%20-F%20key%3Daccess-audit-trail'
                          mode: 420
                          overwrite: true
                          path: /etc/audit/rules.d/75-var-log-kube.rules
                        - contents:
                            source: 'data:,-a%20always%2Cexit%20-F%20dir%3D%2Fvar%2Flog%2Fopenshift-apiserver%2F%20-F%20perm%3Dr%20-F%20auid%3E%3D1000%20-F%20auid!%3Dunset%20-F%20key%3Daccess-audit-trail'
                          mode: 420
                          overwrite: true
                          path: /etc/audit/rules.d/75-var-log-ocp.rules
                        - contents:
                            source: 'data:,-a%20always%2Cexit%20-F%20dir%3D%2Fvar%2Flog%2Foauth-apiserver%2F%20-F%20perm%3Dr%20-F%20auid%3E%3D1000%20-F%20auid!%3Dunset%20-F%20key%3Daccess-audit-trail'
                          mode: 420
                          overwrite: true
                          path: /etc/audit/rules.d/75-var-log-oauth.rules