apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: spoke-cluster-config
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: argoproj.io
      kind: Application
    - group: argoproj.io
      kind: ApplicationSet