---
# https://medium.com/@mprzygrodzki/argocd-applicationsset-with-helm-72bb6362d494
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kyverno
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  kyverno: enabled
          - list:
              elements:
              - appName: kyverno
                namespace: kyverno
                helmRepoURL: 'https://kyverno.github.io/kyverno'
                helmChartName: kyverno
                helmRevision: 3.4.1
  template:
    metadata:
      name: "{{name}}-{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
        argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true 
    spec:
      project: default
      sources:
        - chart: '{{helmChartName}}'
          helm:
            values: |
              webhookLabels:
                app.kubernetes.io/managed-by: argocd
            #valueFiles:
            #  - "$values/75-gitops/{{name}}/helm-values/{{name}}.yaml"
          repoURL: '{{helmRepoURL}}'
          targetRevision: '{{helmRevision}}'
        #- ref: values
        #  repoURL: 'https://github.com/kenmoini/ztp-for-you-and-me'
        #  targetRevision: main
      destination:
        name: "{{name}}"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 2