---
# https://medium.com/@mprzygrodzki/argocd-applicationsset-with-helm-72bb6362d494
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kyverno
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  appset/kyverno: enabled
          - list:
              elements:
              - appName: kyverno
                namespace: kyverno
                helmRepoURL: 'https://kyverno.github.io/kyverno'
                helmChartName: kyverno
                helmRevision: 3.5.2
  template:
    metadata:
      name: "{{name}}-{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
        argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
    spec:
      ignoreDifferences:
        - group: apiextensions.k8s.io
          jsonPointers:
            - /status
            - /status/storedVersions
            - /status/storedVersions/0
            - /status/storedVersions/1
          kind: CustomResourceDefinition
      project: default
      sources:
        - kustomize: {}
          repoURL: 'https://github.com/kenmoini/lab-ocp'
          ## Path is the repo directory that containers the cluster(s) configuration and deployment manifests
          path: configuration/kyverno-policies
    
        - chart: '{{helmChartName}}'
          helm:
            values: |
              config:
                preserve: false
              reportsController:
                resources:
                  requests:
                    cpu: 100m
                    memory: 256Mi
                  limits:
                    cpu: 500m
                    memory: 512Mi
              webhookLabels:
                app.kubernetes.io/managed-by: argocd
            #valueFiles:
            #  - "$values/75-gitops/{{name}}/helm-values/{{name}}.yaml"
          repoURL: '{{helmRepoURL}}'
          targetRevision: '{{helmRevision}}'
        #- ref: values
        #  repoURL: 'https://github.com/kenmoini/ztp-for-you-and-me'
        #  targetRevision: main
      destination:
        name: "{{name}}"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - SkipDryRunOnMissingResource=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
          - ApplyOutOfSyncOnly=true
        retry:
          limit: 2
