---
# https://medium.com/@mprzygrodzki/argocd-applicationsset-with-helm-72bb6362d494
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hub-dev-services
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - key: local-cluster
                    operator: In
                    values:
                      - "true"
                  - key: policy.kemo.dev/developer-services
                    operator: In
                    values:
                      - "true"
                      - "enabled"
          - list:
              elements:
              - appName: hub-dev-svcs
                namespace: openshift-gitops
  template:
    metadata:
      name: "{{name}}-{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
        argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
    spec:
      ignoreDifferences:
        - group: apiextensions.k8s.io
          jsonPointers:
            - /status
          kind: CustomResourceDefinition
        # For some reason ArgoCD marks Applications as OutOfSync due to metadata.generation changes
        - group: 'argoproj.io'
          kind: 'Application'
          jsonPointers:
            - '/metadata/generation'
        - group: 'argoproj.io'
          kind: 'ApplicationSet'
          jsonPointers:
            - '/metadata/generation'
      project: hub-cluster
      sources:
        - kustomize: {}
          repoURL: 'https://github.com/kenmoini/lab-ocp'
          path: tekton/
    
      destination:
        name: "{{name}}"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - SkipDryRunOnMissingResource=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
          - ApplyOutOfSyncOnly=true
        retry:
          limit: 5
