---
# https://medium.com/@mprzygrodzki/argocd-applicationsset-with-helm-72bb6362d494
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: egress-ips
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  appset/egress-ips: enabled
          - list:
              elements:
              - appName: egress-ips
                helmRepoURL: 'https://github.com/kenmoini/helm-things'
                helmChartPath: 'egressip'
                valuesRepo: 'https://github.com/kenmoini/lab-ocp'
                valuesPath: "$values/clusters/{{name}}/helm-values/egressips.yaml"
  template:
    metadata:
      name: "{{name}}-{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: default
      sources:
        - path: '{{helmChartPath}}'
          helm:
            valueFiles:
              - "{{valuesPath}}"
          repoURL: '{{helmRepoURL}}'
        - ref: values
          repoURL: '{{valuesRepo}}'
          targetRevision: HEAD
      destination:
        name: "{{name}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 2