---
# https://medium.com/@mprzygrodzki/argocd-applicationsset-with-helm-72bb6362d494
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: github-arc
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - key: appset/helm-github-arc
                    operator: In
                    values:
                      - "true"
                      - "enable"
                      - "enabled"
          - list:
              elements:
              - appName: arc
                scaleSetAppName: arc-ss
                namespace: arc-systems
                helmRepoURL: 'ghcr.io/actions/actions-runner-controller-charts'
                helmChartName: gha-runner-scale-set-controller
                scaleSetHelmChartName: gha-runner-scale-set
                helmRevision: 0.14.2
  template:
    metadata:
      name: "{{name}}-{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
        argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
    spec:
      ignoreDifferences:
        - group: apiextensions.k8s.io
          jsonPointers:
            - /status
          kind: CustomResourceDefinition
      project: default
      sources:
        - chart: '{{helmChartName}}'
          repoURL: '{{helmRepoURL}}'
          targetRevision: '{{helmRevision}}'
          helm:
            releaseName: '{{appName}}'
            valuesObject:
              metrics:
                controllerManagerAddr: ":8080"
                listenerAddr: ":8080"
                listenerEndpoint: "/metrics"

        - chart: '{{scaleSetHelmChartName}}'
          repoURL: '{{helmRepoURL}}'
          targetRevision: '{{helmRevision}}'
          helm:
            releaseName: '{{scaleSetAppName}}'
            parameters:
              - name: "githubConfigSecret"
                value: kemo-labs-ocp-arc
              - name: "githubConfigUrl"
                value: https://github.com/kenmoini/lab-ocp
              - name: "controllerServiceAccount.name"
                value: arc-gha-rs-controller
              - name: "controllerServiceAccount.namespace"
                value: arc-systems
            valuesObject:
              runnerScaleSetName: tri-force # This is what the runs-on should be in the GHA Workflow
              template:
                spec:
                  hostUsers: false # Enable User Namespaces
                  containers:
                  - name: runner
                    image: ghcr.io/actions/actions-runner:latest
                    command: ["/home/runner/run.sh"]
                    env:
                      - name: ACTIONS_RUNNER_CONTAINER_HOOKS
                        value: /home/runner/k8s/index.js
                      - name: ACTIONS_RUNNER_POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                        value: "true"
                    volumeMounts:
                      - name: work
                        mountPath: /home/runner/_work
                  volumes:
                    - name: work
                      ephemeral:
                        volumeClaimTemplate:
                          spec:
                            accessModes: [ "ReadWriteOnce" ]
                            # storageClassName: "ocs-storagecluster-ceph-rbd"
                            resources:
                              requests:
                                storage: 10Gi
            #valueFiles:
            #  - "$values/clusters/{{name}}/helm-values/{{appName}}.yaml"
        #- ref: values
        #  repoURL: 'https://github.com/kenmoini/lab-ocp'
        #  targetRevision: main
      destination:
        name: "{{name}}"
        namespace: "{{namespace}}"
      syncPolicy:
        # managedNamespaceMetadata:
        #   labels: # The labels to set on the application namespace
        #     security.openshift.io/scc.podSecurityLabelSync: 'false'
        #     pod-security.kubernetes.io/enforce: privileged
        #     pod-security.kubernetes.io/audit: privileged
        #     pod-security.kubernetes.io/warn: privileged
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - SkipDryRunOnMissingResource=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 5
