---
# https://medium.com/@mprzygrodzki/argocd-applicationsset-with-helm-72bb6362d494
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kagent
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  appset/helm-kagent: enabled
          - list:
              elements:
              - appName: kagent
                namespace: kagent
                helmRepoURL: 'oci://ghcr.io/kagent-dev/kagent/helm/kagent'
                helmChartName: kagent
                helmRevision: 0.7.4
  template:
    metadata:
      name: "{{name}}-{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
        argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
    spec:
      ignoreDifferences:
        - group: apiextensions.k8s.io
          jsonPointers:
            - /status
          kind: CustomResourceDefinition
      project: default
      sources:
    
        - chart: '{{helmChartName}}'
          helm:
            valueFiles:
              - "$values/clusters/{{name}}/helm-values/{{appName}}.yaml"
          repoURL: '{{helmRepoURL}}'
          targetRevision: '{{helmRevision}}'
        - ref: values
          repoURL: 'https://github.com/kenmoini/lab-ocp'
          targetRevision: main
      destination:
        name: "{{name}}"
        namespace: "{{namespace}}"
      syncPolicy:
        # managedNamespaceMetadata:
        #   labels: # The labels to set on the application namespace
        #     security.openshift.io/scc.podSecurityLabelSync: 'false'
        #     pod-security.kubernetes.io/enforce: privileged
        #     pod-security.kubernetes.io/audit: privileged
        #     pod-security.kubernetes.io/warn: privileged
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - SkipDryRunOnMissingResource=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 2
