---
# https://medium.com/@mprzygrodzki/argocd-applicationsset-with-helm-72bb6362d494
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: github-arc
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - key: appset/helm-github-arc
                    operator: In
                    values:
                      - "true"
                      - "enable"
                      - "enabled"
          - list:
              elements:
              - appName: arc
                scaleSetAppName: arc-ss
                namespace: arc-systems
                helmRepoURL: 'ghcr.io/actions/actions-runner-controller-charts'
                helmChartName: gha-runner-scale-set-controller
                scaleSetHelmChartName: gha-runner-scale-set
                helmRevision: 0.14.2
  template:
    metadata:
      name: "{{.name}}-{{.appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
        argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
    spec:
      ignoreDifferences:
        - group: apiextensions.k8s.io
          jsonPointers:
            - /status
          kind: CustomResourceDefinition
      project: default
      sources:
        - chart: '{{.helmChartName}}'
          repoURL: '{{.helmRepoURL}}'
          targetRevision: '{{.helmRevision}}'
          helm:
            releaseName: '{{.appName}}'
            valuesObject:
              metrics:
                controllerManagerAddr: ":8080"
                listenerAddr: ":8080"
                listenerEndpoint: "/metrics"

        - chart: '{{.scaleSetHelmChartName}}'
          repoURL: '{{.helmRepoURL}}'
          targetRevision: '{{.helmRevision}}'
          helm:
            releaseName: '{{.scaleSetAppName}}'
            parameters:
              - name: "githubConfigSecret"
                value: kemo-labs-ocp-arc
              - name: "githubConfigUrl"
                value: https://github.com/kenmoini/lab-ocp
              - name: "controllerServiceAccount.name"
                value: arc-gha-rs-controller
              - name: "controllerServiceAccount.namespace"
                value: arc-systems
            valuesObject:
              runnerScaleSetName: tri-force # This is what the runs-on should be in the GHA Workflow
              template:
                metadata:
                  annotations:
                    openshift.io/scc: nested-container-arc
                    io.kubernetes.cri-o.Devices: "/dev/fuse,/dev/net/tun"
                    io.kubernetes.cri-o.cgroup2-mount-hierarchy-rw: 'true'
                spec:
                  hostUsers: false # Enable User Namespaces
                  initContainers:
                    # Native Sidecar: Docker Daemon (DinD)
                    - name: dind-daemon
                      image: quay.io/kenmoini/fedora-dind:latest
                      imagePullPolicy: Always
                      securityContext:
                        # Used for User Namespaces in OpenShift
                        procMount: Unmasked
                        privileged: true
                        runAsUser: 0
                        runAsGroup: 0
                        runAsNonRoot: false
                        seccompProfile: { type: Unconfined }
                        capabilities:
                          add:
                          - "SETUID"
                          - "SETGID"
                          - "SYS_ADMIN"
                          - "NET_ADMIN"
                          - "MKNOD"
                          - "CHOWN"
                      env:
                        - name: DOCKER_CERT_PATH
                          value: ""
                        - name: DOCKER_TLS_CERTDIR
                          value: ""
                        - name: DOCKER_BUILDKIT_RUNC_COMMAND
                          value: "crun"
                        - name: BUILDKIT_SETUP_CGROUPV2_ROOT
                          value: "0"
                        - name: KUBERNETES_NAMESPACE
                          valueFrom:
                            fieldRef:
                              fieldPath: metadata.namespace
                      command:
                        - sh
                        - -c
                        - |
                          # Disable IPv6 if you want
                          /bin/sysctl -w net.ipv6.conf.all.disable_ipv6=1
                          /bin/sysctl -w net.ipv6.conf.default.disable_ipv6=1
                          
                          # I have no idea what this does but it's needed
                          CG=$(sed 's#^0::##' /proc/self/cgroup)
                          mount --bind /sys/fs/cgroup$CG /sys/fs/cgroup
                          exec dockerd-entrypoint.sh "$@"
                        - --
                      args:
                        - --host=unix:///var/run/docker/docker.sock
                        #- --host=tcp://0.0.0.0:2375 # non-TLS port for Docker daemon
                        #- --host=tcp://0.0.0.0:2376 # TLS port for Docker daemon
                        - --mtu=1400                   # avoids packet drops under the OVN overlay
                        - --tls=false  # disables the TLS for simple testing without needing to gen/share certs
                      volumeMounts:
                        - mountPath: /etc/pki/ca-trust/extracted/pem
                          name: ca-certs
                          readOnly: true
                        - name: docker-sock
                          mountPath: /var/run/docker
                        - name: docker-graph-storage
                          mountPath: /var/lib/docker
                        # - name: docker-certs
                        #   mountPath: /certs
                      # Setting restartPolicy to Always defines this as a native sidecar container
                      restartPolicy: Always
                      tty: true
                      resources:
                        limits: { cpu: "2", memory: 4Gi, ephemeral-storage: 20Gi }
                      startupProbe:
                        exec:
                          command: ["docker", "-H", "unix:///var/run/docker/docker.sock", "info"]
                        periodSeconds: 2
                        failureThreshold: 10

                  containers:
                  - name: runner
                    image: ghcr.io/actions/actions-runner:latest
                    # image: quay.io/kenmoini/gha-runner-ubuntu:latest
                    command: ["/home/runner/run.sh"]
                    imagePullPolicy: Always
                    securityContext:
                      procMount: Unmasked
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop:
                          - ALL
                      runAsNonRoot: true
                      runAsUser: 1001
                      runAsGroup: 123
                    env:
                      - name: ACTIONS_RUNNER_CONTAINER_HOOKS
                        value: /home/runner/k8s/index.js
                      - name: ACTIONS_RUNNER_POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                        value: "false"
                      # - name: RUNNER_NAME
                      #   valueFrom:
                      #     fieldRef:
                      #       fieldPath: metadata.name
                      # - name: RUNNER_REPO
                      #   value: "github.com/kenmoini/lab-ocp"
                      # - name: RUNNER_TOKEN
                      #   value: "$ACTIONS_RUNNER_INPUT_JITCONFIG"
                      - name: DOCKER_TLS_CERTDIR
                        value: ""
                      - name: DOCKER_HOST
                        value: unix:///var/run/docker/docker.sock
                      # - name: DOCKER_TLS_VERIFY
                      #   value: "1"
                    volumeMounts:
                      - name: docker-graph-storage
                        mountPath: /var/lib/docker
                      # - name: docker-certs
                      #   mountPath: /certs
                      - name: work
                        mountPath: /home/runner/_work
                      # - name: tmpwork
                      #   mountPath: /runner
                  volumes:
                    # - name: tmpwork
                    #   emptyDir: {}
                    - name: docker-socket
                      emptyDir: {}
                    - name: docker-graph-storage
                      emptyDir: {}
                    # Shared volume to exchange TLS certs
                    # - name: docker-certs
                    #   emptyDir: {}
                    # Used on OpenShift for automatic CA certificate injection
                    - name: ca-certs
                      configMap:
                        name: ca-certs
                        items:
                          - key: ca-bundle.crt
                            path: tls-ca-bundle.pem
                    # Work volume for the runner
                    - name: work
                      ephemeral:
                        volumeClaimTemplate:
                          spec:
                            accessModes: [ "ReadWriteOnce" ]
                            # storageClassName: "ocs-storagecluster-ceph-rbd"
                            resources:
                              requests:
                                storage: 10Gi
            #valueFiles:
            #  - "$values/clusters/{{.name}}/helm-values/{{.appName}}.yaml"
        #- ref: values
        #  repoURL: 'https://github.com/kenmoini/lab-ocp'
        #  targetRevision: main
      destination:
        #name: "{{name}}"
        name: '{{if ne .name "hub-cluster"}}{{.name}}{{end}}'
        server: '{{if eq .name "hub-cluster"}}https://kubernetes.default.svc{{end}}'
        namespace: "{{.namespace}}"
      syncPolicy:
        # managedNamespaceMetadata:
        #   labels: # The labels to set on the application namespace
        #     security.openshift.io/scc.podSecurityLabelSync: 'false'
        #     pod-security.kubernetes.io/enforce: privileged
        #     pod-security.kubernetes.io/audit: privileged
        #     pod-security.kubernetes.io/warn: privileged
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - SkipDryRunOnMissingResource=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 5
