---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: best-practices
  #namespace: open-cluster-management-policies
spec:
  description: "Kubernetes/OpenShift best practices"
  policies:
    - detect-latest-tag