---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: global-openshift-config
  #namespace: open-cluster-management-policies
spec:
  description: "Global OpenShift configuration policies"
  policies:
    # Policies
    - root-ca-distribution
    - global-base-namespaces
    - cluster-info-header
    - disable-self-provisioner
    - configure-project-template
    - audit-logging-config
    - encrypt-etcd
    - image-vuln-scanning
    - enable-multinetworkpolicy
    - compliance-cis-scan
    - compliance-e8-scan
