---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: health-checks
  #namespace: open-cluster-management-policies
spec:
  description: "Cluster health check signals via ACM Policies"
  policies:
    - health-clusteroperator
    - health-clusterversion
    - health-machineconfigpool
    - health-node