---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: instance-bundle-virt
  #namespace: open-cluster-management-policies
spec:
  description: "Set of policies that will install and configure basic OpenShift Virtualization components"
  policies:
    - instance-nfd
    - instance-nmstate
    - instance-mtv
    - instance-virtualization
