---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: operator-bundle-odf
  #namespace: open-cluster-management-policies
spec:
  description: "Set of policies that will deploy basic OpenShift Data Foundation components"
  policies:
    - instance-lso
    #- instance-odf