apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-policies

resources:
  - compliance/

  - best-practices.yaml
  - developer-services.yaml
  - enhanced-metrics.yaml
  - global-openshift-config.yaml
  - global-hcp-virt-openshift-config.yaml
  - global-openshift-operators.yaml
  - global-hcp-virt-openshift-operators.yaml
  - health-checks.yaml
  - hub-health-checks.yaml
  - infra-selectors.yaml
  - instance-bundle-virt.yaml
  - instance-bundle-nvidia.yaml
  - instance-bundle-odf-lso-bmh.yaml
  - onprem-openshift-config.yaml
  - onprem-openshift-operators.yaml
  - onprem-openshift-compliance.yaml
  - operator-bundle-nvidia.yaml
  - operator-bundle-odf.yaml
  - operator-bundle-virt.yaml
  - openshift-ai.yaml
  - openshift-ai-aws.yaml
  - openshift-ai-azure.yaml


commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true