---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: onprem-openshift-compliance
  #namespace: open-cluster-management-policies
spec:
  description: "On-Premises OpenShift compliance policies"
  policies:
    - compliance-operator-config
    - configure-crypto-policy
    - no-empty-passwords
    - allowed-registries # Needed for E8
    - auditd-configuration
    - rhcos4-sysctls
    - ingress-cipher
    - sshd-configuration
    - imagestream-sets-schedule
    - auditd-log-dir-access
    - auditd-file-del-events
    - auditd-etc-rules
    - auditd-dac-mod
    - auditd-priv-cmds
    - auditd-failed-file-events