---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: openshift-ai-azure
  #namespace: open-cluster-management-policies
spec:
  description: "Red Hat OpenShift AI operators and deployments in Azure"
  policies:
    - operators-rh-dns
    - operators-authorino
    - operators-limitador
    - operators-rhcl
    - operators-rh-cert-manager
    - operators-servicemesh-3
    - operators-serverless
    - operators-rh-kueue-base
    - operators-rh-kueue-1.3
    - operators-lwso-base
    - operators-lwso-1.0
    - operators-jobset-base
    - operators-jobset-1.0
    - operators-rh-otel
    - operators-rh-tempo
    - operators-rh-keda
    - operators-coo
    - operators-rhoai
    - operators-cnpgsql
    - default-gatewayclass
    - instance-serverless
    - instance-leaderworkerset
    - instance-jobset
    # - instance-rhoai3