---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: sandboxed-containers
  #namespace: open-cluster-management-policies
spec:
  description: "Set of policies that will enable OpenShift Sandboxed Containers"
  policies:
    - operators-sandbox-containers
    - instance-sandbox-containers