---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-bond0-ocp-vlan60
spec:
  desiredState:
    ovn:
      bridge-mappings:
        # Mapper per VLAN, different localnet
        - localnet: ocp-vlan60
          bridge: ovs-bond0
          state: present