---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-bond0-iso-vlan86
spec:
  desiredState:
    ovn:
      bridge-mappings:
        # Mapper per VLAN, different localnet
        - localnet: iso-vlan86
          bridge: ovs-bond0
          state: present