---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: instance-leaderworkerset
  #namespace: open-cluster-management-policies
  annotations:
    policy.open-cluster-management.io/description: Deploys a LeaderWorkerSetOperator instance
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-SUB - Operator Installation
spec:
  disabled: false
  policy-templates:

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: instance-leaderworkerset
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.openshift.io/v1
                kind: LeaderWorkerSetOperator
                metadata:
                  name: cluster
                spec:
                  logLevel: Normal
                  managementState: Managed
                  operatorLogLevel: Normal