---
kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-dashboard-clusteroperator-health
  #namespace: openshift-config-managed
  namespace: open-cluster-management-observability
  labels:
    # These two labels make the dashboard show up in the OpenShift Console
    #console.openshift.io/dashboard: 'true'
    #console.openshift.io/odc-dashboard: 'true'
    # These two make it show up in ACM
    cluster.open-cluster-management.io/backup: ''
    grafana-custom-dashboard: 'true'
data:
  clusteroperator-health-dashboard.json: |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "description": "Grafana Dashboard for Openshift Cluster Operator Health",
      "id": 61,
      "title": "Health / Cluster / Cluster Operator",
      "uid": "clusteroperator-health",
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "version": 1,
      "links": [],
      "panels": [
        {
          "collapsed": false,
          "datasource": {
            "uid": "$datasource"
          },
          "gridPos": {
            "h": 1,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 22,
          "panels": [],
          "targets": [
            {
              "datasource": {
                "uid": "$datasource"
              },
              "refId": "A"
            }
          ],
          "title": "Cluster Operators",
          "type": "row"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "000000001"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "fixedColor": "transparent",
                "mode": "thresholds"
              },
              "custom": {
                "align": "auto",
                "cellOptions": {
                  "type": "auto"
                },
                "filterable": false,
                "inspect": false
              },
              "decimals": 2,
              "displayName": "",
              "mappings": [],
              "noValue": "-",
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  }
                ]
              },
              "unit": "short"
            },
            "overrides": [
              {
                "matcher": {
                  "id": "byName",
                  "options": "Value"
                },
                "properties": [
                  {
                    "id": "displayName",
                    "value": "Status"
                  },
                  {
                    "id": "custom.align",
                    "value": "left"
                  },
                  {
                    "id": "color",
                    "value": {
                      "mode": "thresholds"
                    }
                  },
                  {
                    "id": "thresholds",
                    "value": {
                      "mode": "absolute",
                      "steps": [
                        {
                          "color": "green",
                          "value": null
                        },
                        {
                          "color": "red",
                          "value": 0
                        },
                        {
                          "color": "green",
                          "value": 1
                        }
                      ]
                    }
                  },
                  {
                    "id": "decimals"
                  },
                  {
                    "id": "custom.cellOptions",
                    "value": {
                      "type": "color-background"
                    }
                  },
                  {
                    "id": "mappings",
                    "value": [
                      {
                        "options": {
                          "0": {
                            "index": 1,
                            "text": "ERROR"
                          },
                          "1": {
                            "index": 0,
                            "text": "OK"
                          }
                        },
                        "type": "value"
                      }
                    ]
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "version"
                },
                "properties": [
                  {
                    "id": "displayName",
                    "value": "Version"
                  },
                  {
                    "id": "custom.align",
                    "value": "left"
                  },
                  {
                    "id": "custom.minWidth",
                    "value": 50
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "reason"
                },
                "properties": [
                  {
                    "id": "displayName",
                    "value": "Condition"
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "clusterType"
                },
                "properties": [
                  {
                    "id": "displayName",
                    "value": "Cluster Type"
                  },
                  {
                    "id": "custom.align"
                  },
                  {
                    "id": "custom.width"
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "cluster"
                },
                "properties": [
                  {
                    "id": "displayName",
                    "value": "Cluster Name"
                  },
                  {
                    "id": "custom.align",
                    "value": "left"
                  },
                  {
                    "id": "decimals"
                  },
                  {
                    "id": "custom.width",
                    "value": 100
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "clusterID"
                },
                "properties": [
                  {
                    "id": "custom.width"
                  },
                  {
                    "id": "custom.align",
                    "value": "left"
                  },
                  {
                    "id": "decimals"
                  },
                  {
                    "id": "displayName",
                    "value": "Cluster ID"
                  }
                ]
              }
            ]
          },
          "gridPos": {
            "h": 14,
            "w": 24,
            "x": 0,
            "y": 1
          },
          "id": 8,
          "options": {
            "cellHeight": "sm",
            "footer": {
              "countRows": false,
              "fields": "",
              "reducer": [
                "sum"
              ],
              "show": false
            },
            "showHeader": true,
            "sortBy": []
          },
          "pluginVersion": "11.1.5",
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "000000001"
              },
              "editorMode": "code",
              "expr": "cluster_operator_up{cluster=\"$cluster\"}",
              "format": "table",
              "hide": false,
              "instant": true,
              "interval": "",
              "intervalFactor": 2,
              "legendFormat": "",
              "refId": "A",
              "step": 10
            }
          ],
          "title": "Cluster Operators",
          "transformations": [
            {
              "disabled": true,
              "id": "merge",
              "options": {
                "reducers": []
              }
            },
            {
              "id": "filterFieldsByName",
              "options": {
                "include": {
                  "names": [
                    "clusterID",
                    "clusterType",
                    "name",
                    "reason",
                    "version",
                    "Value",
                    "cluster"
                  ]
                }
              }
            }
          ],
          "type": "table"
        }
      ],
      "refresh": "5m",
      "schemaVersion": 39,
      "tags": [
        "kubernetes-mixin",
        "observatorium",
        "clusteroperator",
        "health",
        "cluster"
      ],
      "templating": {
        "list": [
          {
            "current": {
              "selected": false,
              "text": "Observatorium",
              "value": "000000001"
            },
            "hide": 2,
            "includeAll": false,
            "multi": false,
            "name": "datasource",
            "options": [],
            "query": "prometheus",
            "refresh": 2,
            "regex": "",
            "skipUrlSync": false,
            "type": "datasource"
          },
          {
            "current": {
              "selected": false,
              "text": "local-cluster",
              "value": "local-cluster"
            },
            "datasource": {
              "type": "prometheus",
              "uid": "${datasource}"
            },
            "definition": "label_values(cluster)",
            "hide": 0,
            "includeAll": false,
            "label": "Cluster",
            "multi": false,
            "name": "cluster",
            "options": [],
            "query": {
              "qryType": 1,
              "query": "label_values(cluster)",
              "refId": "PrometheusVariableQueryEditor-VariableQuery"
            },
            "refresh": 2,
            "regex": "",
            "skipUrlSync": false,
            "sort": 2,
            "type": "query"
          }
        ]
      },
      "time": {
        "from": "now-3h",
        "to": "now"
      },
      "timepicker": {
        "refresh_intervals": [
          "1m",
          "5m",
          "15m",
          "30m",
          "1h",
          "2h",
          "1d"
        ],
        "time_options": [
          "5m",
          "15m",
          "1h",
          "6h",
          "12h",
          "24h",
          "2d",
          "7d",
          "30d"
        ]
      },
      "timezone": "browser",
      "weekStart": ""
    }