---
apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management-observability
  #labels:
    #openshift.io/cluster-monitoring: "true"
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: acm-observability
  #namespace: open-cluster-management-observability
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  generateBucketName: acm-observability
  objectBucketName: obc-openshift-storage-acm-observability
  storageClassName: openshift-storage.noobaa.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: acm-cli-job-sa-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - patch
  - apiGroups:
      - objectbucket.io
    resources:
      - objectbucketclaims
    verbs:
      - get
      - list
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acm-gitops-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acm-cli-job-sa-role
subjects:
  - kind: ServiceAccount
    name: cli-job-sa
    namespace: open-cluster-management-observability
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cli-job-sa
  #namespace: open-cluster-management-observability