apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - template.yaml
# Not needed since OCPV already provides RHEL images, just need to add the Template
#  - datavolume.yaml
#  - datasource.yaml
