---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-o-c-m-p.yaml
  - global-o-c-m-p.yaml
  # the stackrox namespace must exist for the stackrox policies to work
  #- global-stackrox.yaml