- name: Maths
  hosts: localhost
  gather_facts: false
  vars:
    increment_percentage: 10
    current_size: 1073741824
    current_used: 812675072

  tasks:
  - name: Debug calculation
    ansible.builtin.debug:
      msg:
        - "Current size: {{ current_size }} bytes"
        - "Current size in Gi: {{ (current_size / 1048576 / 1024 ) | round | int }}Gi"
        - "Current used: {{ current_used }} bytes"
        - "Current used in Gi: {{ (current_used / 1048576 / 1024) | round | int }}Gi"
        - "Consumed percentage: {{ (current_used / current_size * 100) | round | int }}%"
        - "Above Warning Threshold: {{ ((current_used / current_size * 100) | round | int) > 75 }}"
        - "Above Critical Threshold: {{ ((current_used / current_size * 100) | round | int) > 85 }}"
        - "Increment Percentage: {{ increment_percentage }}%"
        - "New Size in Gi: {{ (((current_size + ( (current_size / 100) * increment_percentage )) )  / 1048576 / 1024) | round(0, 'ceil') | int }}Gi"
        - "New Size in Bytes: {{ (current_size + ( (current_size / 100) * increment_percentage )) | round | int }} bytes"