---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: argocd-agent-managed
  # namespace: automation-orchestrator
placementRef:
  name: argocd-agent-managed
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: aa-copy-ca
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: aa-spoke-copy-creds
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: aa-agent-managed-instance
    apiGroup: policy.open-cluster-management.io
    kind: Policy