---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: argocd-agent-auto
  # namespace: automation-orchestrator
placementRef:
  name: argocd-agent-auto
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: aa-auto-copy-ca
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: aa-spoke-auto-copy-creds
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: aa-agent-auto-instance
    apiGroup: policy.open-cluster-management.io
    kind: Policy