apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops-operator
  annotations:
    openshift.io/display-name: "OpenShift GitOps Operator"
  labels:
    openshift.io/cluster-monitoring: 'true'
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops
  annotations:
    openshift.io/display-name: "Local cluster ArgoCD instance"
  labels:
    openshift.io/cluster-monitoring: 'true'
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd-agent-managed-clusters
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd