---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: automation-orchestrator

resources:
  - rhoai3_binding.yaml
  - rhoai3.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true