---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: openshift-ai
  # namespace: automation-orchestrator
placementRef:
  name: openshift-ai
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: creds-auto-orch-obc
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: creds-auto-orch-pgsql
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: secret-auto-orch-svcca
    apiGroup: policy.open-cluster-management.io
    kind: Policy