---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: maas-pgsql-db-secret
  # namespace: redhat-ods-applications
spec:
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: policy.kemo.dev/openshift-ai
              operator: In
              values:
                - "true"
                - "enabled"