---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: all-openshift-clusters
  #namespace: open-cluster-management-policies
placementRef:
  name: all-openshift-clusters
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  # Health Signals
  - name: health-clusteroperator
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: health-clusterversion
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: health-machineconfigpool
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: health-node
    apiGroup: policy.open-cluster-management.io
    kind: Policy

  # Configuration
  - name: cluster-info-header
    apiGroup: policy.open-cluster-management.io
    kind: Policy

  # Operator Deployment
  - name: operators-rhacs
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: operators-compliance
    apiGroup: policy.open-cluster-management.io
    kind: Policy