---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: all-openshift-clusters
  #namespace: open-cluster-management-policies
placementRef:
  name: all-openshift-clusters
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  # Health Signals
  - name: health-checks
    apiGroup: policy.open-cluster-management.io
    kind: PolicySet

  # Global OpenShift Configuration
  - name: global-openshift-config
    apiGroup: policy.open-cluster-management.io
    kind: PolicySet

  # Global OpenShift Operator Installation
  - name: global-openshift-operators
    apiGroup: policy.open-cluster-management.io
    kind: PolicySet
