---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: all-openshift-clusters
  #namespace: open-cluster-management-policies
placementRef:
  name: all-openshift-clusters
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  # Health Signals
  - name: health-checks
    apiGroup: policy.open-cluster-management.io
    kind: PolicySet

  # Configuration
  - name: cluster-info-header
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: audit-logging-config
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: encrypt-etcd
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: image-vuln-scanning
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  #- name: kyverno-outbound-proxy
  #  apiGroup: policy.open-cluster-management.io
  #  kind: Policy

  # Operator Deployment
  - name: operators-gitops-base
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: operators-logging-base
    apiGroup: policy.open-cluster-management.io
    kind: Policy

  - name: operators-rhacs
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: operators-metallb
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: instance-metallb
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: operators-web-terminal
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: operators-compliance
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: operators-nmo
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: operators-nmstate
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: instance-nmstate
    apiGroup: policy.open-cluster-management.io
    kind: Policy