---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: azure-self-managed-odf
  #namespace: open-cluster-management-policies
placementRef:
  name: enable-odf-nodes
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: storage-mcp
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: azure-storage-machinesets
    apiGroup: policy.open-cluster-management.io
    kind: Policy

  - name: operators-odf-base
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: operators-odf-variable
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: instance-odf-azure
    apiGroup: policy.open-cluster-management.io
    kind: Policy