---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: global
  #namespace: open-cluster-management-policies
placementRef:
  name: global
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: failing-inform
    apiGroup: policy.open-cluster-management.io
    kind: Policy