---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: hcp-baremetal
  #namespace: open-cluster-management-policies
placementRef:
  name: hcp-baremetal
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  # Configuration
  - name: hcp-bmh-console
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: hcp-openshift-samples-config
    apiGroup: policy.open-cluster-management.io
    kind: Policy
  - name: enable-internal-registry
    apiGroup: policy.open-cluster-management.io
    kind: Policy

  # Operators
  - name: operator-bundle-virt
    apiGroup: policy.open-cluster-management.io
    kind: PolicySet

  # Operator Deployment
  - name: instance-bundle-virt
    apiGroup: policy.open-cluster-management.io
    kind: PolicySet