---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: hub-cluster
  #namespace: open-cluster-management-policies
placementRef:
  name: hub-cluster
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  # Health Signals
  - name: hub-health-checks
    apiGroup: policy.open-cluster-management.io
    kind: PolicySet

  # HCP Integration
  - name: hcp-bmh-acm-infra-creds
    apiGroup: policy.open-cluster-management.io
    kind: Policy

  # Operators
  - name: operators-coo
    apiGroup: policy.open-cluster-management.io
    kind: Policy

  # Hub Instances
  - name: instance-acs-central
    apiGroup: policy.open-cluster-management.io
    kind: Policy