---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: hub-cluster
  #namespace: open-cluster-management-policies
placementRef:
  name: hub-cluster
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  # Health Signals
  - name: health-mc-addons
    apiGroup: policy.open-cluster-management.io
    kind: Policy

  # HCP Integration
  - name: hcp-bmh-acm-infra-creds
    apiGroup: policy.open-cluster-management.io
    kind: Policy

  # Operators
  - name: operators-cco
    apiGroup: policy.open-cluster-management.io
    kind: Policy