apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-policies

resources:
  - all-openshift-clusters.yaml
  - all-hcp-virt-clusters.yaml
  
  - aws-self-managed.yaml
  - aws-self-managed-infra.yaml
  - aws-self-managed-nvidia.yaml
  - aws-self-managed-odf.yaml

  - azure-self-managed.yaml
  - azure-self-managed-infra.yaml
  - azure-self-managed-nvidia.yaml
  - azure-self-managed-odf.yaml

  - onprem-openshift-clusters.yaml
  - openshift-4.19-clusters.yaml
  - openshift-4.20-clusters.yaml
  - openshift-4.21-clusters.yaml
  - acs.yaml
  - enhanced-metrics.yaml
  - global.yaml
  - hcp-baremetal.yaml
  - hcp-inception.yaml
  - hcp-kubevirt.yaml
  - hcp-services.yaml
  - hub-cluster.yaml
  - hub-developer-services.yaml
  - hub-4.19-clusters.yaml
  - hub-4.20-clusters.yaml
  - hub-4.21-clusters.yaml

  - community-eso.yaml
  - bmh-lso-odf.yaml
  - nvidia-gpu.yaml
  - virtualization.yaml
  - rh-loki.yaml
  - developer-services.yaml
  - servicemesh.yaml
  - openshift-ai.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true