---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: secrets-rhdh-argocd
  namespace: openshift-gitops
  annotations:
    policy.open-cluster-management.io/description: Namespaced policy for mutation of ArgoCD secrets for RHDH instance
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-INST - Operator Instance
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rhdh-argocd-secrets
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: argocd-secrets
                  namespace: rhdh
                type: Opaque
                data:
                  ARGOCD_URL: '{{ (cat "https://" (lookup "route.openshift.io/v1" "Route" "openshift-gitops" "openshift-gitops-server").spec.host) | replace " " "" | base64enc  }}'
                  ARGOCD_USERNAME: '{{ fromSecret "openshift-gitops" "rhdh-local-user" "user" }}'
                  ARGOCD_PASSWORD: '{{ fromSecret "openshift-gitops" "rhdh-local-user" "apiToken" }}'