---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: maas-pgsql-db-secret
  namespace: redhat-ods-applications
  annotations:
    policy.open-cluster-management.io/description: Reconfigures the MaaS PostgreSQL Secret into a new one to be used by RHOAI
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-INST - Operator Instance
spec:
  disabled: false
  policy-templates:
    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: maas-pgsql-instance
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: maas-pgsql-db-secret
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: maas-db-config
                  namespace: redhat-ods-applications
                type: Opaque
                data:
                  DB_CONNECTION_URL: '{{ (cat (fromSecret "redhat-ods-applications" "maas-db-app" "fqdn-uri") "?sslmode=disable") | base64enc }}'
                  # Example using hub function to pull from a Secret in the hub cluster
                  #DB_CONNECTION_URL: '{{hub fromSecret "redhat-ods-applications" "maas-db-app" "fqdn-uri" hub}}'
