---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: maas-o11y-cfg-to-secret
  namespace: redhat-ods-monitoring
  annotations:
    policy.open-cluster-management.io/description: Reconfigures the MaaS PostgreSQL Secret into a new one to be used by RHOAI
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-INST - Operator Instance
spec:
  disabled: false
  policy-templates:
    # Check for the ConfigMap that we're copying from
    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: Policy
          name: operators-rhoai
          namespace: ""
          compliance: Compliant
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: rhoai-dsci-check
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rhoai-o11y-cmap-check
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: default-dsci
    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: rhoai-o11y-cmap-check
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: maas-o11y-cfg-to-secret
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: prometheus-web-tls-ca
                  namespace: redhat-ods-monitoring
                type: Opaque
                data:
                  ca.crt: '{{ fromConfigMap "redhat-ods-monitoring" "prometheus-web-tls-ca" "service-ca.crt" }}'
                  # Example using hub function to pull from a Secret in the hub cluster
                  # service-ca.crt: '{{hub fromConfigMap "redhat-ods-monitoring" "prometheus-web-tls-ca" "service-ca.crt" hub}}'
