---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: netobserv-loki-format-obc-secret
  namespace: netobserv
  annotations:
    policy.open-cluster-management.io/description: Reconfigures the Loki OBC Secret into a new one to be used by the Network Observability Loki instances
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-INST - Operator Instance
spec:
  disabled: false
  policy-templates:
    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: netobserv-loki-obc
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: netobserv-loki-obc-secret
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: netobserv-loki-s3
                  namespace: netobserv
                type: Opaque
                data:
                  # Example using hub function to pull from a Secret in the hub cluster
                  #access_key_id: '{{hub fromSecret "netobserv" "netobserv-loki" "AWS_ACCESS_KEY_ID" hub}}'
                  #access_key_secret: '{{hub fromSecret "netobserv" "netobserv-loki" "AWS_SECRET_ACCESS_KEY" hub}}'
                  #bucketnames: '{{hub (lookup "objectbucket.io/v1alpha1" "ObjectBucketClaim" "netobserv" "netobserv-loki").spec.bucketName | base64enc hub}}'
                  access_key_id: '{{ fromSecret "netobserv" "netobserv-loki" "AWS_ACCESS_KEY_ID" }}'
                  access_key_secret: '{{ fromSecret "netobserv" "netobserv-loki" "AWS_SECRET_ACCESS_KEY" }}'
                  bucketnames: '{{ "netobserv-loki" | base64enc }}'
                  endpoint: '{{ "https://s3.openshift-storage.svc" | base64enc }}'
                  region: '{{ "the-moon" | base64enc }}'
