---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: secrets-rhdh-kc
  namespace: rhbk
  annotations:
    policy.open-cluster-management.io/description: Namespaced policy for mutation of RHDH secrets for Keycloak instance
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-INST - Operator Instance
spec:
  disabled: false
  policy-templates:
    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: eso-vault-clustersecretstore
          namespace: ""
          compliance: Compliant
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: keycloak-instance
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rhdh-kc-secrets
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: external-secrets.io/v1beta1
                kind: ExternalSecret
                metadata:
                  name: vault-rhdh-keycloak-client
                  # This is created in the keycloak NS because that's where the instance and RealmImport are
                  namespace: rhdh
                spec:
                  refreshInterval: "3600s"
                  secretStoreRef:
                    name: kemo-labs-vault
                    kind: ClusterSecretStore
                  target:
                    name: keycloak-client # name of the k8s Secret to make in this namespace
                    creationPolicy: Owner
                    deletionPolicy: Retain
                    template:
                      engineVersion: v2
                      type: Opaque # type of k8s Secret to make
                  data:
                    - secretKey: KEYCLOAK_BASE_URL
                      remoteRef:
                        key: kemo.labs/oauth/keycloak/rhdh # name of the secret under the target Vault path
                        property: keycloakBaseURL # name of the key in that named Vault secret
                    - secretKey: KEYCLOAK_CLIENT_ID
                      remoteRef:
                        key: kemo.labs/oauth/keycloak/rhdh
                        property: clientID
                    - secretKey: KEYCLOAK_CLIENT_SECRET
                      remoteRef:
                        key: kemo.labs/oauth/keycloak/rhdh
                        property: clientSecret
                    - secretKey: KEYCLOAK_LOGIN_REALM
                      remoteRef:
                        key: kemo.labs/oauth/keycloak/rhdh
                        property: keycloakRealm
                    - secretKey: KEYCLOAK_REALM
                      remoteRef:
                        key: kemo.labs/oauth/keycloak/rhdh
                        property: keycloakRealm
            - complianceType: musthave
              objectDefinition:
                apiVersion: external-secrets.io/v1beta1
                kind: ExternalSecret
                metadata:
                  name: vault-rhdh-keycloak-client
                  # This is created in the keycloak NS because that's where the instance and RealmImport are
                  namespace: rhbk
                spec:
                  refreshInterval: "3600s"
                  secretStoreRef:
                    name: kemo-labs-vault
                    kind: ClusterSecretStore
                  target:
                    name: keycloak-client # name of the k8s Secret to make in this namespace
                    creationPolicy: Owner
                    deletionPolicy: Retain
                    template:
                      engineVersion: v2
                      type: Opaque # type of k8s Secret to make
                  data:
                    - secretKey: KEYCLOAK_BASE_URL
                      remoteRef:
                        key: kemo.labs/oauth/keycloak/rhdh # name of the secret under the target Vault path
                        property: keycloakBaseURL # name of the key in that named Vault secret
                    - secretKey: KEYCLOAK_CLIENT_ID
                      remoteRef:
                        key: kemo.labs/oauth/keycloak/rhdh
                        property: clientID
                    - secretKey: KEYCLOAK_CLIENT_SECRET
                      remoteRef:
                        key: kemo.labs/oauth/keycloak/rhdh
                        property: clientSecret
                    - secretKey: KEYCLOAK_LOGIN_REALM
                      remoteRef:
                        key: kemo.labs/oauth/keycloak/rhdh
                        property: keycloakRealm
                    - secretKey: KEYCLOAK_REALM
                      remoteRef:
                        key: kemo.labs/oauth/keycloak/rhdh
                        property: keycloakRealm
            - complianceType: musthave
              objectDefinition:
                apiVersion: external-secrets.io/v1beta1
                kind: ExternalSecret
                metadata:
                  name: vault-rhdh-rhgoogle-client
                  # This is created in the keycloak NS because that's where the instance and RealmImport are
                  namespace: rhbk
                spec:
                  refreshInterval: "3600s"
                  secretStoreRef:
                    name: kemo-labs-vault
                    kind: ClusterSecretStore
                  target:
                    name: rhdh-rhgoogle-client # name of the k8s Secret to make in this namespace
                    creationPolicy: Owner
                    deletionPolicy: Retain
                    template:
                      engineVersion: v2
                      type: Opaque # type of k8s Secret to make
                  data:
                    - secretKey: clientID
                      remoteRef:
                        key: external/google/oauth # name of the secret under the target Vault path
                        property: clientID # name of the key in that named Vault secret
                    - secretKey: clientSecret
                      remoteRef:
                        key: external/google/oauth # name of the secret under the target Vault path
                        property: clientSecret # name of the key in that named Vault secret
    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: rhdh-kc-secrets
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rhdh-rhbk-realm
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: k8s.keycloak.org/v2alpha1
                kind: KeycloakRealmImport
                metadata:
                  name: rhdh-realm
                  namespace: rhbk
                spec:
                  keycloakCRName: sso
                  realm:
                    id: rhdh
                    realm: rhdh
                    displayName: "Red Hat Developer Hub Realm"
                    enabled: true
                    sslRequired: external
                    loginWithEmailAllowed: true
                    duplicateEmailsAllowed: false
                    identityProviderMappers:
                      - name: googlerhsso
                        identityProviderAlias: rhgooglesso
                        identityProviderMapper: oidc-hardcoded-group-idp-mapper
                        config:
                          syncMode: INHERIT
                          group: /rhdh-users

                    identityProviders:
                      - alias: rhgooglesso
                        displayName: RH Google SSO
                        providerId: google
                        enabled: true
                        updateProfileFirstLoginMode: 'on'
                        trustEmail: true
                        storeToken: false
                        addReadTokenRoleOnCreate: false
                        authenticateByDefault: false
                        linkOnly: false
                        hideOnLogin: false
                        config:
                          acceptsPromptNoneForwardFromClient: 'false'
                          clientId: '{{ fromSecret "rhbk" "rhdh-rhgoogle-client" "clientID" | base64dec }}'
                          disableUserInfo: 'false'
                          showInAccountConsole: ALWAYS
                          filteredByClaim: 'false'
                          hostedDomain: redhat.com
                          syncMode: LEGACY
                          clientSecret: '{{ fromSecret "rhbk" "rhdh-rhgoogle-client" "clientSecret" | base64dec }}'
                          caseSensitiveOriginalUsername: 'false'
                          prompt: select_account

                    # Users
                    users:
                      # - username: admin
                      #   enabled: true
                      #   email: admin@ultra.lab
                      #   firstName: Admin
                      #   lastName: User
                      #   credentials:
                      #     - type: password
                      #       value: admin
                      #       temporary: false
                      #   groups:
                      #     - /rhdh-admins
                      #     - /rhdh-users
                      # - username: user1
                      #   enabled: true
                      #   email: user1@ultra.lab
                      #   firstName: User
                      #   lastName: One
                      #   credentials:
                      #     - type: password
                      #       value: user1
                      #       temporary: false
                      #   groups:
                      #     - /rhdh-users
                      # Service account for RHDH client - needs realm-management roles
                      - username: service-account-rhdh
                        enabled: true
                        serviceAccountClientId: rhdh
                        clientRoles:
                          realm-management:
                            - view-users
                            - query-groups
                            - query-users
                    # Groups
                    groups:
                      - name: rhdh-users
                        path: /rhdh-users
                      - name: rhdh-admins
                        path: /rhdh-admins
                    # Clients
                    clients:
                      - clientId: rhdh
                        name: RHDH Client
                        description: Red Hat Developer Hub OIDC Client
                        enabled: true
                        protocol: openid-connect
                        publicClient: false
                        standardFlowEnabled: true
                        directAccessGrantsEnabled: true
                        serviceAccountsEnabled: true
                        secret: keycloak-client
                        redirectUris:
                          - '{{ (fromClusterClaim "consoleurl.cluster.open-cluster-management.io") | replace "console-openshift-console" "backstage-dev-hub-rhdh" }}/api/auth/oidc/handler/frame'
                        webOrigins:
                          # Can't use a route lookup because the dev hub instance hasn't been created yet at this point
                          #- 'https://{{ (lookup "route.openshift.io/v1" "Route" "rhdh" "backstage-dev-hub-rhdh").spec.host }}'
                          - '{{ (fromClusterClaim "consoleurl.cluster.open-cluster-management.io") | replace "console-openshift-console" "backstage-dev-hub-rhdh" }}'
                        defaultClientScopes:
                          - web-origins
                          - acr
                          - profile
                          - roles
                          - email
                        optionalClientScopes:
                          - address
                          - phone
                          - offline_access
                          - microprofile-jwt
