---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: secrets-rhdh-rhdh
  namespace: rhdh
  annotations:
    policy.open-cluster-management.io/description: Namespaced policy for mutation of RHDH secrets for RHDH instance
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-INST - Operator Instance
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rhdh-rhdh-secrets
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: my-rhdh-secrets
                  namespace: rhdh
                type: Opaque
                data:
                  BACKEND_SECRET: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName | base64enc }}'
                  BACKEND_URL: '{{ (fromClusterClaim "consoleurl.cluster.open-cluster-management.io") | replace "console-openshift-console" "backstage-dev-hub-rhdh" | base64enc }}'

                  # TLS configuration
                  NODE_TLS_REJECT_UNAUTHORIZED: MA==                      # "0" to disable TLS verification (dev only)

                  # # GitHub App Integration
                  # GITHUB_INTEGRATION_APP_ID: <base64-encoded-app-id>
                  # GITHUB_INTEGRATION_CLIENT_ID: <base64-encoded-client-id>
                  # GITHUB_INTEGRATION_CLIENT_SECRET: <base64-encoded-client-secret>
                  # GITHUB_INTEGRATION_HOST_DOMAIN: <base64-encoded-domain> # e.g., github.com
                  # GITHUB_INTEGRATION_ORGANIZATION: <base64-encoded-org>   # Your GitHub org name
                  # GITHUB_INTEGRATION_PRIVATE_KEY_FILE: <base64-encoded-private-key-pem>