FROM registry.access.redhat.com/ubi9/ubi:latest

ARG RUNNER_VERSION="2.337.0"

RUN useradd -m docker && \
    dnf update -y --disablerepo="rhel-9*" && \
    dnf install -y --disablerepo="rhel-9*" ca-certificates curl-minimal jq wget dnf-plugins-core && \
    dnf config-manager --set-disabled "rhel-9*" && \
    dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo && \
    dnf install -y --disablerepo="rhel-9*" docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin && \
    dnf clean all && \
    rm -rf /var/cache/dnf

# Setup GitHub Actions runner
RUN cd /home/docker && mkdir actions-runner && cd actions-runner \
    && curl -O -L https://github.com/actions/runner/releases/download/v${RUNNER_VERSION}/actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz \
    && tar xzf ./actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz

RUN dnf config-manager --set-disabled rhel-9* && \
    chown -R docker ~docker && /home/docker/actions-runner/bin/installdependencies.sh

# Add Internal Root CAs
COPY root-ca/* /etc/pki/ca-trust/source/anchors/
RUN update-ca-trust

# Default to a non-root user
USER docker
