---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/kenmoini/ocp-o11y/refs/heads/main/openshift/alertmanager-config/base/debug-receiver.yml