---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-default-cronjob
  annotations:
    policies.kyverno.io/title: Add Default CronJob spec
    policies.kyverno.io/subject: CronJob
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: A Kyverno policy to add a default spec to CronJob resources that do not have one defined.
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.10.0-alpha.2
    kyverno.io/kubernetes-version: "1.26"
spec:
  background: false
  rules:
    - name: add-default-history
      match:
        any:
          - resources:
              kinds:
                - CronJob
      preconditions:
        any:
          - key: "{{request.operation || 'BACKGROUND'}}"
            operator: AnyIn
            value:
              - CREATE
              - UPDATE
      mutate:
        patchStrategicMerge:
          spec:
            +(successfulJobsHistoryLimit): 3
            +(failedJobsHistoryLimit): 3