apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: deny-access-to-protected-resources
  annotations:
    policies.kyverno.io/title: Deny Access to Protected Resources
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod,Secret,ConfigMap
    kyverno.io/kyverno-version: 1.9.0
    policies.kyverno.io/minversion: 1.9.0
    kyverno.io/kubernetes-version: "1.24"
    policies.kyverno.io/description: >-
      This policy denies access to resources labeled with `kyverno.io/protected=true`
      unless the user or group is explicitly allowed. This helps protect sensitive
      resources from unauthorized access. Users or groups listed in the exclude section
      are permitted to access these protected resources.
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: block-access-to-protected-content
      match:
        any:
        - resources:
            kinds:
              - Pod
              - Secret
              - ConfigMap
            selector:
              matchLabels:
                kyverno.io/protected: "true"
      exclude:
        any:
        - subjects:
          - kind: Group
            name: cluster-admins
          - kind: User
            name: ken@kenmoini.com
          - kind: User
            name: kemo
          - kind: User
            name: kmoini@redhat.com
      preconditions:
        all:
        - key: "{{request.operation || 'BACKGROUND'}}"
          operator: NotEquals
          value: DELETE
      validate:
        message: "Access to protected resources is denied."
        deny:
          conditions:
            any:
              - key: "{{request.name}}"
                operator: Equals
                value: '*'