apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
    vm.kubevirt.io/validations: |
      [
        {
          "name": "minimal-required-memory",
          "path": "jsonpath::.spec.domain.memory.guest",
          "rule": "integer",
          "message": "This VM requires more memory.",
          "min": 1610612736
        }
      ]
  name: control-plane-1
  finalizers:
    - kubevirt.io/virtualMachineControllerFinalize
  labels:
    app: control-plane-1
    redfish-enabled: 'true'
    kubevirt.io/dynamic-credentials-support: 'true'
    vm.kubevirt.io/template: rhel9-highperformance-large
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.34.0
spec:
  runStrategy: Halted
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: control-plane-1
      spec:
        source:
          blank: {}
        storage:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 120Gi
          storageClassName: ocs-storagecluster-ceph-rbd
          volumeMode: Block
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: large
        vm.kubevirt.io/os: rhcos9
        vm.kubevirt.io/workload: highperformance
        descheduler.alpha.kubernetes.io/evict: 'true'
      creationTimestamp: null
      labels:
        kubevirt.io/domain: control-plane-1
        kubevirt.io/size: large
        redfish-enabled: 'true'
        network.kubevirt.io/headlessService: headless
    spec:
      networks:
        - multus:
            networkName: default/vmnet70-disconnected
          name: mgmt
      volumes:
        - dataVolume:
            name: control-plane-1
          name: rootdisk
      domain:
        memory:
          guest: 16Gi
        cpu:
          sockets: 8
          cores: 1
          threads: 1
          dedicatedCpuPlacement: true
          isolateEmulatorThread: true
        devices:
          disks:
            - name: rootdisk
              bootOrder: 2
              dedicatedIOThread: true
              disk:
                bus: virtio
          interfaces:
            - bridge: {}
              model: virtio
              name: mgmt
              state: up
          networkInterfaceMultiqueue: true
          rng: {}
        ioThreadsPolicy: shared
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel9.6.0
        resources: {}
      architecture: amd64
      evictionStrategy: LiveMigrate
      terminationGracePeriodSeconds: 180