---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-policies

resources:
  - auditd-configuration.yaml
  - rhcos-crypto-policy.yaml
  - rhcos-no-empty-passwords.yaml
  - allowed-registries.yaml
  - ingresscontroller-cipher-suites.yaml