---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: acs-secured-cluster
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: acs-secured-cluster
              operator: In
              values:
                - "true"
                - "enabled"