---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: appset-helm-github-arc
spec:
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: appset/helm-github-arc
              operator: In
              values:
                - "true"
                - "enable"
                - "enabled"