---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: aws-self-managed
  #namespace: open-cluster-management-policies
spec:
  clusterSets:
    - aws-self-managed
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists