---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: enhanced-metrics
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: policy.kemo.dev/enhanced-metrics
              operator: In
              values:
                - "true"
                - "enabled"