apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Let's just use the built-in templates and just add the datavolume and CA configmap
  #- template.yaml
  - datavolume.yaml
  #- root-ca-configmap.yaml