---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: infra-selector-imgreg
  annotations:
    policy.open-cluster-management.io/description: Moves the OpenShift Image Registry to infrastructure nodes
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: infra-selector-imgreg
        spec:
          remediationAction: enforce
          severity: low
          object-templates-raw: |
            {{/* ##  Loop through all the Nodes ## */}}
            {{- $nodeList := (lookup "v1" "Node" "" "").items }}
            {{- $infraNodesDetected := false }}
            {{- range $node := $nodeList }}
              {{- if (hasKey $node.metadata.labels "node-role.kubernetes.io/infra") }}
                {{- $infraNodesDetected = true }}
              {{- end -}}
            {{- end }}
            {{- if $infraNodesDetected }}
            {{/* ## Patch the ImageRegistry Config ## */}}
            - complianceType: musthave
              objectDefinition:
                apiVersion: imageregistry.operator.openshift.io/v1
                kind: Config
                metadata:
                  name: cluster
                spec:
                  nodeSelector:
                    node-role.kubernetes.io/infra: ""
                  tolerations:
                    - key: node-role.kubernetes.io/infra
                      operator: Exists
                      effect: NoSchedule
                    - key: node-role.kubernetes.io/infra
                      operator: Exists
                      effect: NoExecute
            {{- end }}