---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - maaspolicy-admins.yaml
  - maassubscription.yaml
  - nvidia-gpu-hardwareprofile.yaml
  - phi-4-mini-instruct.llmis.yaml
  - phi-4-mini-instruct.llmisc.yaml
  - phi-4-mini-instruct.httproute.yaml
  - phi-4-mini-instruct.msmr.yaml
  - rhoai-monitoring-netpol.yaml
  - upstream/

# namespace: test-maas