apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSAuthPolicy
metadata:
  annotations:
    openshift.io/display-name: admins
  name: admins
  namespace: models-as-a-service
spec:
  modelRefs:
    - name: redhataiphi-4-mini-instruct-fp
      namespace: test-maas
    - name: "simulated-free"
      namespace: "ai-models"
    - name: "simulated-premium"
      namespace: "ai-models"
      # tokenRateLimits:
      #   redhataiphi-4-mini-instruct-fp:
      #     - limit: 100000
      #       window: 1m
  subjects:
    groups:
      - name: cluster-admins
      - name: rhods-admins
    users:
      - kemo