apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSModelRef
metadata:
  annotations:
    openshift.io/display-name: RedHatAI/Phi-4-mini-instruct-FP8-dynamic
  name: redhataiphi-4-mini-instruct-fp
  namespace: test-maas
spec:
  modelRef:
    kind: LLMInferenceService
    name: redhataiphi-4-mini-instruct-fp