---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: aa-copy-ca
  # namespace: argocd-principal
  annotations:
    policy.open-cluster-management.io/description: Distributes the CA certificate for the ArgoCD Agent Principal to Managed Clusters
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2026
    policy.open-cluster-management.io/controls: OLM-SUB - Operator Installation
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: aa-copy-ca
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: argocd-agent-ca
                  namespace: 'argocd-agent-{{ .ManagedClusterName }}'
                type: Opaque
                data:
                  ca.crt: '{{hub (lookup "v1" "Secret" "argocd-principal" "argocd-agent-ca").data.tls.crt hub}}'
