---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-principal

resources:

  # Hub/Principal - Reformat JWT secret
  - gitops-agent-principal-jwt-formatting.yaml

  # Hub/Principal - Copy CA to Agent Spoke Clusters
  - gitops-agent-auto-copy-ca.yaml
  - gitops-agent-managed-copy-ca.yaml

  # Hub/Principal - Generate Spoke Cluster Certificates
  - gitops-agent-create-certs.yaml

  # Agent Spoke - Copy Cluster Credentials to Agent Spoke Clusters
  - gitops-spoke-credentials.yaml

  # Agent Spoke - Instances
  - gitops-agent-auto-instance.yaml
  - gitops-agent-managed-instance.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true