---
- name: Create PDNS Record from ZTP HCP Virt API LoadBalancer Service Rulebook
  hosts: all
  match_multiple_rules: true
  execution_strategy: sequential
  sources:
    - juniper.eda.k8s:
        validate_certs: false
        api_version: v1
        kind: Service
        label_selectors:
          - hypershift.openshift.io/control-plane-component=kube-apiserver

  rules:
    # - name: debug more lol
    #   condition: true
    #   action:
    #     debug:

    - name: LoadBalancer Service Detected
      condition: (event.type == "ADDED" or event.type == "MODIFIED") and event.resource.spec.type == "LoadBalancer" and event.resource.status.loadBalancer.ingress is defined
      action:
        run_workflow_template:
          name: EDA Workflow - Create PowerDNS Record from HCP Virt Service
          organization: Default

    # - name: debug lol
    #   condition: true
    #   action:
    #     print_event:
    #       pretty: true
