---
- name: Create PDNS Record from LoadBalancer Service Rulebook
  hosts: all
  match_multiple_rules: true
  execution_strategy: sequential
  sources:
    - sabre1041.eda.k8s:
        validate_certs: false
        api_version: v1
        kind: Service
        # label_selectors:
        #   - hypershift.openshift.io/control-plane-component=kube-apiserver

  rules:
    - name: debug more lol
      condition: true
      action:
        debug:
        
    - name: LoadBalancer Service Detected
      condition: (event.type == "ADDED" or event.type == "MODIFIED") and event.resource.spec.type == "LoadBalancer"
      action:
        run_job_template:
          name: Create PDNS Record
          organization: Default

    # - name: LoadBalancer Service Modified
    #   condition: event.type == "MODIFIED"
    #   action:
    #     run_job_template:
    #       name: Create PDNS Record
    #       organization: Default
          
    - name: debug lol
      condition: true
      action:
        print_event:
          pretty: true
