# Shamelessly stolen from https://github.com/bry-tam/acm-policy-samples/blob/main/policies/cluster-health/clusteroperator.yml
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: health-check-noobaa
  #namespace: open-cluster-management-observability
  annotations:
    policy.open-cluster-management.io/description: Check for the presence of the NooBaa StorageClass and raise a policy violation if it is not present.
    policy.open-cluster-management.io/categories: O11Y - OpenShift Observability
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: CH - Cluster Health
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: ocmo-health-check-noobaa
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: storage.k8s.io/v1
                kind: StorageClass
                metadata:
                  name: openshift-storage.noobaa.io