---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: e8
  #namespace: open-cluster-management-policies
spec:
  description: "Australian Cyber Security Centre (ACSC) Essential Eight Remediation"
  policies:
    - configure-crypto-policy
    - no-empty-passwords