---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - stig-platform.yaml
  - 800-53-high.yaml
  - cis.yaml
  - e8.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true