---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: v60-auto-pool
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  addresses:
    - 192.168.60.20-192.168.60.30
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: v60-high-pool
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  addresses:
    - 192.168.60.100-192.168.60.150
  autoAssign: false