---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ztp-hcp-virt-ztp-cluster
  namespace: openshift-gitops
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
spec:
  ignoreDifferences:
    - group: hive.openshift.io
      jsonPointers:
        - /spec/installed
      kind: ClusterDeployment
    - group: hive.openshift.io
      jsonPointers:
        - /spec
      kind: ClusterDeployment
    - group: extensions.hive.openshift.io
      jsonPointers:
        - /spec
      kind: AgentClusterInstall
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .spec.data[].remoteRef.conversionStrategy
        - .spec.data[].remoteRef.decodingStrategy
        - .spec.data[].remoteRef.metadataPolicy
  destination:
    name: hub-cluster
  sources:
    - repoURL: 'https://github.com/kenmoini/lab-ocp.git'
      targetRevision: main
      path: ztp-clusters/hub-cluster/spokes/hcp-virt-ztp-cluster/
      kustomize: {}
  project: ztp-clusters
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: false
    retry:
      limit: 2