---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ztp-hcp-kubevirt
  namespace: openshift-gitops
spec:
  ignoreDifferences:
    - group: hive.openshift.io
      jsonPointers:
        - /spec/installed
      kind: ClusterDeployment
    - group: hive.openshift.io
      jsonPointers:
        - /spec
      kind: ClusterDeployment
    - group: extensions.hive.openshift.io
      jsonPointers:
        - /spec
      kind: AgentClusterInstall
  destination:
    name: hub-cluster
  sources:
    - repoURL: 'https://github.com/kenmoini/lab-ocp.git'
      targetRevision: main
      path: ztp-clusters/hub-cluster/spokes/hcp-kubevirt/
      kustomize: {}
  project: ztp-clusters
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: false
    retry:
      limit: 2