---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-policies

resources:

  # Operator Installation Policies
  - mtv/
  - gitops-base.yaml
  - gitops-1.18.yaml

  - logging-base.yaml
  - logging-6.3.yaml
  - logging-6.4.yaml
  - logging-6.5.yaml

  - rh-loki-base.yaml
  - rh-loki-6.3.yaml
  - rh-loki-6.4.yaml
  - rh-loki-6.5.yaml

  - mtc-base.yaml
  - mtc-1.8.yaml

  - aap-base.yaml
  - aap-2.6.yaml
  - aap-2.7.yaml

  - rhbk-base.yaml
  - rhbk-26.4.yaml
  - rhbk-26.6.yaml

  - rh-kueue-base.yaml
  - rh-kueue-v1.3.yaml

  - leader-workset-base.yaml
  - leader-workset-v1.0.yaml

  - jobset-base.yaml
  - jobset-v1.0.yaml

  - quay-3.16.yaml
  - quay-3.17.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
