---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: operators-lwso-base
  #namespace: open-cluster-management-policies
  annotations:
    policy.open-cluster-management.io/description: Installs the Red Hat Leader Workset Operator base components
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2026
    policy.open-cluster-management.io/controls: OLM-SUB - Operator Installation
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rh-lwso-ns
        spec:
          remediationAction: enforce
          severity: critical
          pruneObjectBehavior: None
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-lws-operator
                  labels:
                    openshift.io/cluster-monitoring: 'true'
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rh-lwso-og
        spec:
          remediationAction: enforce
          severity: high
          pruneObjectBehavior: None
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: rh-lwso-operator-group
                  namespace: openshift-lws-operator
                spec:
                  upgradeStrategy: Default