---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: operators-logging-base
  #namespace: open-cluster-management-policies
  annotations:
    policy.open-cluster-management.io/description: Installs the OpenShift Logging Operator
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-SUB - Operator Installation
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: logging-namespace
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-logging
                  labels:
                    openshift.io/cluster-monitoring: 'true'
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: logging-operator-group
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: logging-operator-group
                  namespace: openshift-logging
                spec:
                  upgradeStrategy: Default
          pruneObjectBehavior: None

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: logging-rbac
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ServiceAccount
                metadata:
                  name: logging-collector
                  namespace: openshift-logging

            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: logging-loki-collector
                subjects:
                  - kind: ServiceAccount
                    name: logging-collector
                    namespace: openshift-logging
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: logging-collector-logs-writer

            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: logging-loki-app-logs
                subjects:
                  - kind: ServiceAccount
                    name: logging-collector
                    namespace: openshift-logging
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: collect-application-logs

            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: logging-loki-infra-logs
                subjects:
                  - kind: ServiceAccount
                    name: logging-collector
                    namespace: openshift-logging
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: collect-infrastructure-logs

            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: logging-loki-audit-logs
                subjects:
                  - kind: ServiceAccount
                    name: logging-collector
                    namespace: openshift-logging
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: collect-audit-logs
