---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: operators-4.19-mtc-1.8
  #namespace: open-cluster-management-policies
  annotations:
    policy.open-cluster-management.io/description: Installs the OpenShift Migration Toolkit for Containers Operator v1.8 on OCP 4.19 clusters
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-SUB - Operator Installation
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: mtc-1.8-subscription
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: mtc-operator
                  namespace: openshift-migration
                spec:
                  channel: release-v1.8
                  installPlanApproval: Automatic
                  name: mtc-operator
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
      extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: mtc-namespace
          namespace: ""
          compliance: Compliant
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: mtc-operator-group
          namespace: ""
          compliance: Compliant
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: mtc-operator-install-check
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: ClusterServiceVersion
                metadata:
                  namespace: openshift-migration
                spec:
                  displayName: Migration Toolkit for Containers Operator
                status:
                  phase: Succeeded
                  reason: InstallSucceeded
      extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: mtc-1.8-subscription
          namespace: ""
          compliance: Compliant

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: mtc-1.8-controller
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: migration.openshift.io/v1alpha1
                kind: MigrationController
                metadata:
                  name: migration-controller
                  namespace: openshift-migration
                spec:
                  mig_namespace_limit: '10'
                  migration_ui: true
                  mig_pod_limit: '100'
                  migration_controller: true
                  migration_log_reader: true
                  olm_managed: true
                  cluster_name: host
                  restic_timeout: 1h
                  migration_velero: true
                  mig_pv_limit: '100'
                  azure_resource_group: ''
      extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: mtc-operator-install-check
          namespace: ""
          compliance: Compliant