---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: operators-rh-loki-base
  #namespace: open-cluster-management-policies
  annotations:
    policy.open-cluster-management.io/description: Installs the Red Hat Loki Operator
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-SUB - Operator Installation
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rh-loki-namespace
        spec:
          remediationAction: enforce
          severity: critical
          namespaceSelector:
            include:
              - openshift-operators-redhat
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-operators-redhat
                  labels:
                    openshift.io/cluster-monitoring: 'true'
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: operators-redhat-operator-group
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: operators-redhat-operator-group
                  namespace: openshift-operators-redhat
                spec:
                  upgradeStrategy: Default
          pruneObjectBehavior: DeleteIfCreated
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: operators-redhat-operator-mcsb
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                # This lets us bootstrap the Policy to mux credentials
                apiVersion: cluster.open-cluster-management.io/v1beta2
                kind: ManagedClusterSetBinding
                metadata:
                  name: global
                  namespace: openshift-operators-redhat
                spec:
                  clusterSet: global
            - complianceType: musthave
              objectDefinition:
                # This lets us bootstrap the Policy to mux credentials
                apiVersion: cluster.open-cluster-management.io/v1beta2
                kind: ManagedClusterSetBinding
                metadata:
                  name: global
                  namespace: openshift-logging
                spec:
                  clusterSet: global
