---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: operators-rh-loki-6.3
  #namespace: open-cluster-management-policies
  annotations:
    policy.open-cluster-management.io/description: Installs the Red Hat Loki stable-6.3 Operator
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-SUB - Operator Installation
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rh-loki-6.3-subscription
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: loki-operator
                  namespace: openshift-operators-redhat
                spec:
                  channel: stable-6.3
                  installPlanApproval: Automatic
                  name: loki-operator
                  source: redhat-operators 
                  sourceNamespace: openshift-marketplace
