ARG UPSTREAM_IMAGE=quay.io/kenmoini/kl-golden-ubi:latest

################################################################################

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest AS postgresql_container_source

RUN microdnf -y --setopt=tsflags=nodocs install git
RUN git clone --depth 1 https://github.com/sclorg/postgresql-container /postgresql-container

FROM ${UPSTREAM_IMAGE} AS base

ENV POSTGRESQL_VERSION=18 \
    POSTGRESQL_PREV_VERSION=17 \
    HOME=/var/lib/pgsql \
    PGUSER=postgres \
    APP_DATA=/opt/app-root

ENV SUMMARY="PostgreSQL is an advanced Object-Relational database management system" \
    DESCRIPTION="PostgreSQL is an advanced Object-Relational database management system (DBMS). \
The image contains the client and server programs that you'll need to \
create, run, maintain and access a PostgreSQL DBMS server."

LABEL summary="$SUMMARY" \
      description="$DESCRIPTION" \
      io.k8s.description="$DESCRIPTION" \
      io.k8s.display-name="PostgreSQL 18" \
      io.openshift.expose-services="5432:postgresql" \
      io.openshift.tags="database,postgresql,postgresql18,postgresql-18" \
      io.openshift.s2i.assemble-user="26" \
      name="rhel9/postgresql-$POSTGRESQL_VERSION" \
      com.redhat.component="postgresql-18-container" \
      version="$POSTGRESQL_VERSION" \
      com.redhat.license_terms="https://www.redhat.com/en/about/red-hat-end-user-license-agreements#rhel" \
      usage="podman run -d --name postgresql_database -e POSTGRESQL_USER=user -e POSTGRESQL_PASSWORD=pass -e POSTGRESQL_DATABASE=db -p 5432:5432 rhel9/postgresql-18" \
      maintainer="SoftwareCollections.org <sclorg@redhat.com>"

EXPOSE 5432

COPY --from=postgresql_container_source /postgresql-container/13/root/usr/libexec/fix-permissions /usr/libexec/fix-permissions

# This image must forever use UID 26 for postgres user so our volumes are
# safe in the future. This should *never* change, the last test is there
# to make sure of that.
RUN dnf -y --disableplugin=subscription-manager --setopt=tsflags=nodocs update && \
    (dnf info postgresql-server); \
    if [ $? == 1 ]; then \
      ARCH=$(uname -m) && \
      dnf -y --setopt=protected_packages= remove redhat-release && \
      dnf -y remove *subscription-manager* && \
      dnf -y install \
        http://mirror.stream.centos.org/9-stream/BaseOS/${ARCH}/os/Packages/centos-stream-release-9.0-24.el9.noarch.rpm \
        http://mirror.stream.centos.org/9-stream/BaseOS/${ARCH}/os/Packages/centos-stream-repos-9.0-24.el9.noarch.rpm \
        http://mirror.stream.centos.org/9-stream/BaseOS/${ARCH}/os/Packages/centos-gpg-keys-9.0-24.el9.noarch.rpm && \
      dnf clean all && \
      rm -rf /var/cache/dnf; \
    fi && \
    { yum -y module enable postgresql:13 || :; } && \
    INSTALL_PKGS="rsync tar gettext bind-utils nss_wrapper postgresql-server postgresql-contrib" && \
    yum -y --setopt=tsflags=nodocs install $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    postgres -V | grep -qe "$POSTGRESQL_VERSION\." && echo "Found VERSION $POSTGRESQL_VERSION" && \
    (yum -y reinstall tzdata || yum -y update tzdata ) && \
    yum -y clean all --enablerepo='*' && \
    localedef -f UTF-8 -i en_US en_US.UTF-8 && \
    chmod -R g+w /etc/pki/tls && \
    test "$(id postgres)" = "uid=26(postgres) gid=26(postgres) groups=26(postgres)" && \
    mkdir -p /var/lib/pgsql/data && \
    mkdir -p /run/postgresql && \
    /usr/libexec/fix-permissions /var/lib/pgsql /run/postgresql
