---
apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSAuthPolicy
metadata:
  name: admins-models-policy
  namespace: models-as-a-service
spec:
  modelRefs:
    - name: redhataiphi-4-mini-instruct-fp
      namespace: test-maas
  subjects:
    groups:
      - name: cluster-admins
      - name: rhods-admins