---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: community-eso
  namespace: kube-system
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: community-eso
              operator: In
              values:
                - "true"
                - "enabled"