---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: maas-pgsql-db-secret
  namespace: redhat-ods-applications
placementRef:
  name: maas-pgsql-db-secret
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: maas-pgsql-db-secret
    apiGroup: policy.open-cluster-management.io
    kind: Policy