---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: maas-o11y-cfg-to-secret
  namespace: redhat-ods-monitoring
placementRef:
  name: maas-o11y-cfg-to-secret
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: maas-o11y-cfg-to-secret
    apiGroup: policy.open-cluster-management.io
    kind: Policy
