---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: netobserv-loki
  namespace: netobserv
spec:
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: policy.kemo.dev/enhanced-metrics
              operator: In
              values:
                - "true"
                - "enabled"