---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: all-openshift-clusters
  namespace: openshift-monitoring
placementRef:
  name: all-openshift-clusters
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: configure-monitoring
    apiGroup: policy.open-cluster-management.io
    kind: Policy