---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: operators-aap
  annotations:
    policy.open-cluster-management.io/description: Installs the Ansible Automation Platform Operator
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-SUB - Operator Installation
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: aap-namespace
        spec:
          remediationAction: enforce
          severity: critical
          namespaceSelector:
            include:
              - aap
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: aap
                  labels:
                    openshift.io/cluster-monitoring: 'true'
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: aap-operator-group
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: aap-group
                  namespace: aap
                spec:
                  upgradeStrategy: Default
          pruneObjectBehavior: DeleteIfCreated
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: aap-subscription
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: ansible-automation-platform-operator
                  namespace: aap
                spec:
                  channel: stable-2.5-cluster-scoped
                  installPlanApproval: Automatic
                  name: ansible-automation-platform-operator
                  source: redhat-operators 
                  sourceNamespace: openshift-marketplace
