---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: operators-agent-sandbox
  annotations:
    policy.open-cluster-management.io/description: Installs the Agent Sandbox Operator
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2026
    policy.open-cluster-management.io/controls: OLM-SUB - Operator Installation
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: agent-sandbox-ns
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: agent-sandbox-system
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: agent-sandbox-og
        spec:
          remediationAction: enforce
          severity: high
          pruneObjectBehavior: DeleteIfCreated
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: agent-sandbox
                  namespace: agent-sandbox-system
                spec:
                  upgradeStrategy: Default
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: agent-sandbox-sub
        spec:
          remediationAction: enforce
          severity: high
          pruneObjectBehavior: DeleteIfCreated
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: agent-sandbox-operator
                  namespace: agent-sandbox-system
                spec:
                  channel: preview-0.9
                  installPlanApproval: Automatic
                  name: agent-sandbox-operator
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
