---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: operators-auto-orch
  annotations:
    policy.open-cluster-management.io/description: Installs the Automation Orchestrator Operator
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2026
    policy.open-cluster-management.io/controls: OLM-SUB - Operator Installation
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: auto-orch-ns
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: automation-orchestrator
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: auto-orch-og
        spec:
          remediationAction: enforce
          severity: high
          pruneObjectBehavior: DeleteIfCreated
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: automation-orchestrator-og
                  namespace: automation-orchestrator
                spec:
                  upgradeStrategy: Default
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: auto-orch-sub
        spec:
          remediationAction: enforce
          severity: high
          pruneObjectBehavior: DeleteIfCreated
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: automation-orchestrator-operator
                  namespace: automation-orchestrator
                spec:
                  channel: stable
                  installPlanApproval: Automatic
                  name: automation-orchestrator-operator
                  source: redhat-operators 
                  sourceNamespace: openshift-marketplace

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: auto-orch-netpols
        spec:
          remediationAction: enforce
          severity: high
          pruneObjectBehavior: DeleteIfCreated
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: networking.k8s.io/v1
                kind: NetworkPolicy
                metadata:
                  name: allow-kube-apiserver
                  namespace: automation-orchestrator
                spec:
                  egress:
                    - to:
                      - namespaceSelector:
                          matchLabels:
                            kubernetes.io/metadata.name: openshift-kube-apiserver
                        podSelector:
                          matchLabels:
                            app: openshift-kube-apiserver
                  # ingress:
                  #   - from:
                  #     - namespaceSelector:
                  #         matchLabels:
                  #           kubernetes.io/metadata.name: openshift-kube-apiserver
                  #       podSelector:
                  #         matchLabels:
                  #           app: openshift-kube-apiserver
                  policyTypes:
                    # - Ingress
                    - Egress
            - complianceType: musthave
              objectDefinition:
                apiVersion: networking.k8s.io/v1
                kind: NetworkPolicy
                metadata:
                  name: allow-same-namespace
                  namespace: automation-orchestrator
                spec:
                  podSelector: {} # Selects all pods in this namespace
                  policyTypes:
                    - Ingress
                    - Egress
                  ingress:
                    - from:
                      - podSelector: {} # Allows ingress from all pods in this same namespace
                  egress:
                    - to:
                      - podSelector: {} # Allows egress to all pods in this same namespace

    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: auto-orch-sub
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: auto-orch-op-check
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: automation-orchestrator-operator-controller-manager
                  namespace: automation-orchestrator
                status:
                  conditions:
                    - status: 'True'
                      type: Available