---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: operators-cco
  annotations:
    policy.open-cluster-management.io/description: Installs the Cluster Observability Operator
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-SUB - Operator Installation
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cco-namespace
        spec:
          remediationAction: enforce
          severity: critical
          namespaceSelector:
            include:
              - openshift-cluster-observability-operator
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-cluster-observability-operator
                  labels:
                    openshift.io/cluster-monitoring: 'true'
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cco-operator-group
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: cco-group
                  namespace: openshift-cluster-observability-operator
                spec:
                  upgradeStrategy: Default
          pruneObjectBehavior: DeleteIfCreated
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cco-subscription
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: cluster-observability-operator
                  namespace: openshift-cluster-observability-operator
                spec:
                  channel: stable
                  installPlanApproval: Automatic
                  name: cluster-observability-operator
                  source: redhat-operators 
                  sourceNamespace: openshift-marketplace
