---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: operators-cost-mgmt
  annotations:
    policy.open-cluster-management.io/description: Installs the OpenShift Cost Management Metrics Operator
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-SUB - Operator Installation
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-cmm-namespace
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: costmanagement-metrics-operator
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-cmm-operatorgroup
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: openshift-cmm-operatorgroup
                  namespace: costmanagement-metrics-operator
                spec:
                  targetNamespaces:
                    - costmanagement-metrics-operator
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-cmm-subscription
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: costmanagement-metrics-operator
                  namespace: costmanagement-metrics-operator
                spec:
                  channel: stable
                  installPlanApproval: Automatic
                  name: costmanagement-metrics-operator
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace