---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-policies

resources:
  - observability/
  - workload-availability/

  # - aap.yaml -- REPLACED BY VERSIONED OPERATOR POLICIES --
  # AI Things
  - agent-sandbox.yaml
  - sandbox-containers.yaml
  - rhoai.yaml

  # Developer Things
  - authorino.yaml
  - dev-hub.yaml
  - devspaces.yaml
  - limitador.yaml
  - openshift-builds.yaml
  - pipelines.yaml
  - serverless.yaml
  - servicemesh-3.yaml
  - servicemesh-2.yaml
  - rhcl.yaml

  # Security Things
  - cert-manager.yaml
  - community-eso.yaml
  - compliance.yaml
  - file-integrity.yaml

  # Hub things
  - automation-orchestrator.yaml
  - cnpgsql.yaml
  - gatekeeper.yaml
  - talm.yaml

  # Platform/Infrastructure Things
  - keda.yaml
  - lso.yaml
  - metallb.yaml
  # - mtv.yaml
  - nfd.yaml
  - nmstate.yaml
  - nvidia-gpu.yaml
  - oadp.yaml
  - odf.yaml
  - rhacs.yaml
  - rh-dns.yaml
  - sscsi.yaml
  - truenas-csi.yaml
  - virtualization.yaml
  - web-terminal.yaml
  - zero-trust-wim.yaml


commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true