---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: operators-node-healthcheck
  annotations:
    policy.open-cluster-management.io/description: Installs the Node Healthcheck Operator
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-SUB - Operator Installation
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: nhco-namespace
        spec:
          remediationAction: enforce
          severity: critical
          namespaceSelector:
            include:
              - openshift-workload-availability
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-workload-availability
                  labels:
                    openshift.io/cluster-monitoring: "true"
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: nhco-group
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: openshift-workload-availability
                  namespace: openshift-workload-availability
                spec:
                  upgradeStrategy: Default
          pruneObjectBehavior: None
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: nhco-subscription
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: node-healthcheck-operator
                  namespace: openshift-workload-availability
                spec:
                  channel: stable
                  installPlanApproval: Automatic
                  name: node-healthcheck-operator
                  source: redhat-operators 
                  sourceNamespace: openshift-marketplace
