---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: operators-rh-dns
  annotations:
    policy.open-cluster-management.io/description: Installs the Red Hat DNS Operator
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-SUB - Operator Installation
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rh-dns-subscription
        spec:
          remediationAction: enforce
          severity: high
          pruneObjectBehavior: DeleteIfCreated
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: dns-operator
                  namespace: openshift-operators
                spec:
                  channel: stable
                  installPlanApproval: Manual
                  name: dns-operator
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
                  startingCSV: dns-operator.v1.3.1

    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: rh-dns-subscription
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rh-dns-status
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: dns-operator-controller-manager
                  namespace: openshift-operators
                status:
                  conditions:
                    - status: 'True'
                      type: Available
