---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: operators-talm
  annotations:
    policy.open-cluster-management.io/description: Installs the Topology Aware Lifecycle Manager (TALM) Operator
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-SUB - Operator Installation
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: talm-subscription
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: openshift-topology-aware-lifecycle-manager-subscription
                  namespace: openshift-operators
                spec:
                  channel: stable
                  installPlanApproval: Automatic
                  name: topology-aware-lifecycle-manager
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
