---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: automation-orchestrator

resources:
  - creds-auto-orch-pgsql.yaml
  - creds-auto-orch-obc.yaml
  - service-ca-secret.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true