---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: secret-auto-orch-svcca
  # namespace: automation-orchestrator
  annotations:
    policy.open-cluster-management.io/description: Copies the Service CA ConfigMap to a Secret because Ansible engineers don't know how OpenShift works...
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2026
    policy.open-cluster-management.io/controls: OLM-INST - Operator Instance
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: secret-auto-orch-svcca
        spec:
          remediationAction: enforce
          severity: critical
          pruneObjectBehavior: DeleteIfCreated
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: s3-ca-cert
                  namespace: automation-orchestrator
                type: Opaque
                data:
                  ca.crt: '{{ fromConfigMap "automation-orchestrator" "openshift-service-ca.crt" "service-ca.crt" | base64enc }}'
