apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: operators-mtv-2.9
  annotations:
    policy.open-cluster-management.io/description: Installs the Migration Toolkit for Virtualization Operator version 2.9
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-SUB - Operator Installation
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: mtv-subscription
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: mtv-operator
                  namespace: openshift-mtv
                spec:
                  channel: release-v2.9
                  installPlanApproval: Automatic
                  name: mtv-operator
                  source: redhat-operators 
                  sourceNamespace: openshift-marketplace
