---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: aa-agent-managed
  # namespace: open-cluster-management-policies
  annotations:
    policy.open-cluster-management.io/description: Bootstraps the ArgoCD Agent Spoke Instance in Managed Mode.
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2026
    policy.open-cluster-management.io/controls: OLM-SUB - Operator Installation
spec:
  disabled: false
  dependencies:
    - apiVersion: policy.open-cluster-management.io/v1
      kind: Policy
      name: gitops-agent-spoke
      namespace: open-cluster-management-policies
      compliance: Compliant
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: agent-managed-ns
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: "argocd-agent-{{hub .ManagedClusterName hub}}"

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: agent-managed-netpol
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: networking.k8s.io/v1
                kind: NetworkPolicy
                metadata:
                  name: custom-agent-redis-network-policy
                  namespace: "argocd-agent-{{hub .ManagedClusterName hub}}"
                spec:
                  podSelector:
                    matchLabels:
                      app.kubernetes.io/name: agent-argocd-redis
                  ingress:
                    - ports:
                        - protocol: TCP
                          port: 6379
                      from:
                        - podSelector:
                            matchLabels:
                              app.kubernetes.io/name: argocd-agent-agent
                  policyTypes:
                    - Ingress

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: agent-managed-appproj
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: argoproj.io/v1alpha1
                kind: AppProject
                metadata:
                  name: default
                  namespace: "argocd-agent-{{hub .ManagedClusterName hub}}"
                spec:
                  clusterResourceWhitelist:
                    - group: '*'
                      kind: '*'
                  destinations:
                    - namespace: '*'
                      server: '*'
                  sourceRepos:
                    - '*'

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: agent-managed-argocd
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: argoproj.io/v1beta1
                kind: ArgoCD
                metadata:
                  name: agent-argocd
                  namespace: "argocd-agent-{{hub .ManagedClusterName hub}}"
                spec:
                  server:
                    enabled: false
                  argoCDAgent:
                    agent:
                      allowedNamespaces:
                        - '*'
                      enabled: true
                      client:
                        principalServerAddress: '{{hub (lookup "route.openshift.io/v1" "Route" "argocd-principal" "hub-argocd-agent-principal").spec.host hub}}'
                        principalServerPort: "443"
                        mode: managed