---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Install the Operator
  - operators-gitops-agent-principal.yaml
  - operators-gitops-agent-spoke.yaml

  # Hub/Principal - Initialize PKI
  - gitops-agent-principal-bootstrap.yaml

  # Spoke/Managed - Initialize Agent Instance
  - gitops-agent-managed.yaml

  # Spoke/Autonomous - Initialize Agent Instance
  - gitops-agent-auto.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true