---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: gitops-agent-spoke
  #namespace: open-cluster-management-policies
  annotations:
    policy.open-cluster-management.io/description: Installs the OpenShift GitOps Operator in Agent Mode on the Spoke/Managed Cluster
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2026
    policy.open-cluster-management.io/controls: OLM-SUB - Operator Installation
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: agent-spoke-ns
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-gitops
                  labels:
                    openshift.io/cluster-monitoring: "true"
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-gitops-operator
                  labels:
                    openshift.io/cluster-monitoring: "true"

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: agent-spoke-og
        spec:
          remediationAction: enforce
          severity: high
          pruneObjectBehavior: DeleteIfCreated
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: openshift-gitops-operator
                  namespace: openshift-gitops-operator
                spec:
                  upgradeStrategy: Default

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: agent-spoke-sub
        spec:
          remediationAction: enforce
          severity: high
          pruneObjectBehavior: DeleteIfCreated
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: openshift-gitops-operator
                  namespace: openshift-gitops-operator
                spec:
                  channel: latest
                  installPlanApproval: Automatic
                  name: openshift-gitops-operator
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
                  config:
                    env:
                      - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
                        value: '*'
                      # - name: DISABLE_DEFAULT_ARGOCD_INSTANCE
                      #   value: "true"
                      # - name: DISABLE_DEFAULT_ARGOCD_CONSOLELINK
                      #   value: "true"
