apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: enable-hostedcontrolplane
  #namespace: open-cluster-management-policies
  annotations:
    policy.open-cluster-management.io/categories: OCPCM - OpenShift Configuration Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: CC - Capability Configuration
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: enable-wildcard-ingress
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.openshift.io/v1
                kind: IngressController
                metadata:
                  name: default
                  namespace: openshift-ingress-operator
                spec:
                  routeAdmission:
                    wildcardPolicy: WildcardsAllowed
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-for-acm-mce
        spec:
          remediationAction: inform
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.open-cluster-management.io/v1
                kind: MultiClusterHub
                metadata:
                  namespace: open-cluster-management
            - complianceType: musthave
              objectDefinition:
                apiVersion: multicluster.openshift.io/v1
                kind: MultiClusterEngine