---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: failing-inform
  #namespace: open-cluster-management-policies
  annotations:
    policy.open-cluster-management.io/description: Raises policy violation for a non-existing namespace
    policy.open-cluster-management.io/categories: O11Y - OpenShift Observability
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: CH - Cluster Health
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-namespace
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: i-do-not-exist
          remediationAction: inform
          severity: low
