apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: gha-controller
  #namespace: open-cluster-management-policies
  annotations:
    policy.open-cluster-management.io/categories: OCPCM - OpenShift Configuration Management
    policy.open-cluster-management.io/standards: Kemo Labs 2026
    policy.open-cluster-management.io/controls: CC - Capability Configuration
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gha-ns-meta
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Namespace
                apiVersion: v1
                metadata:
                  name: arc-systems
                  annotations:
                    openshift.io/sa.scc.supplemental-groups: 1000/10000
                    openshift.io/sa.scc.uid-range: 1000/10000
    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: eso-vault-clustersecretstore
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gha-ext-secret
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: external-secrets.io/v1beta1
                kind: ExternalSecret
                metadata:
                  name: gha-controller
                  namespace: arc-systems
                spec:
                  refreshInterval: "3600s"
                  secretStoreRef:
                    name: kemo-labs-vault
                    kind: ClusterSecretStore
                  target:
                    name: kemo-labs-ocp-arc # name of the k8s Secret to make in this namespace
                    creationPolicy: Owner
                    deletionPolicy: Retain
                    template:
                      engineVersion: v2
                      type: Opaque # type of k8s Secret to make
                  data:
                    - secretKey: github_app_id
                      remoteRef:
                        key: external/github/arc # name of the secret under the target Vault path
                        property: github_app_id # # name of the key in that named Vault secret
                    - secretKey: github_app_installation_id
                      remoteRef:
                        key: external/github/arc # name of the secret under the target Vault path
                        property: github_app_installation_id # # name of the key in that named Vault secret
                    - secretKey: github_app_private_key
                      remoteRef:
                        key: external/github/arc # name of the secret under the target Vault path
                        property: github_app_private_key # # name of the key in that named Vault secret

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gha-rbac
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: arc-ss-init
                  namespace: arc-systems
                rules:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                      - secrets
                    verbs:
                      - get
                      - list
                      - create
                      - delete
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    subresources:
                      - exec
                    verbs:
                      - get
                      - create
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    subresources:
                      - log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - "batch"
                    resources:
                      - jobs
                    verbs:
                      - get
                      - list
                      - create
                      - delete
            - complianceType: musthave
              objectDefinition:
                kind: RoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: gharc-userns
                  namespace: arc-systems
                subjects:
                  - kind: ServiceAccount
                    name: arc-gha-rs-controller
                    namespace: arc-systems
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: 'system:openshift:scc:restricted-v3'
            - complianceType: musthave
              objectDefinition:
                kind: RoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: gharc-ss-init
                  namespace: arc-systems
                subjects:
                  - kind: ServiceAccount
                    name: arc-gha-rs-controller
                    namespace: arc-systems
                  - kind: ServiceAccount
                    name: tri-force-gha-rs-no-permission
                    namespace: arc-systems
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: Role
                  name: 'arc-ss-init'
