apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: gha-controller
  #namespace: open-cluster-management-policies
  annotations:
    policy.open-cluster-management.io/categories: OCPCM - OpenShift Configuration Management
    policy.open-cluster-management.io/standards: Kemo Labs 2026
    policy.open-cluster-management.io/controls: CC - Capability Configuration
spec:
  disabled: false
  policy-templates:
    # - objectDefinition:
    #     apiVersion: policy.open-cluster-management.io/v1
    #     kind: ConfigurationPolicy
    #     metadata:
    #       name: gha-rbac-scc
    #     spec:
    #       remediationAction: enforce
    #       severity: low
    #       object-templates:
    #         - complianceType: musthave
    #           objectDefinition:
    #             apiVersion: rbac.authorization.k8s.io/v1
    #             kind: ClusterRole
    #             metadata:
    #               name: system:openshift:scc:github-arc
    #             rules:
    #             - apiGroups:
    #               - security.openshift.io
    #               resourceNames:
    #               - github-arc
    #               resources:
    #               - securitycontextconstraints
    #               verbs:
    #               - use
    #         - complianceType: musthave
    #           objectDefinition:
    #             kind: SecurityContextConstraints
    #             metadata:
    #               annotations:
    #                 kubernetes.io/description: Based on restricted SCC, but forces uid/gid 1001/123
    #               name: github-arc
    #             allowHostDirVolumePlugin: false
    #             allowHostIPC: false
    #             allowHostNetwork: false
    #             allowHostPID: false
    #             allowHostPorts: false
    #             allowPrivilegeEscalation: true
    #             allowPrivilegedContainer: false
    #             allowedCapabilities: null
    #             apiVersion: security.openshift.io/v1
    #             defaultAddCapabilities: null
    #             userNamespaceLevel: RequirePodLevel
    #             fsGroup:
    #               ranges:
    #               - max: 65534
    #                 min: 123
    #               type: MustRunAs
    #             groups: []
    #             priority: null
    #             readOnlyRootFilesystem: false
    #             requiredDropCapabilities:
    #             - KILL
    #             - MKNOD
    #             - SETUID
    #             - SETGID
    #             runAsUser:
    #               type: MustRunAs
    #               uid: 1001
    #             seLinuxContext:
    #               type: MustRunAs
    #             supplementalGroups:
    #               ranges:
    #               - max: 123
    #                 min: 123
    #               type: MustRunAs
    #             users: []
    #             volumes:
    #             - configMap
    #             - csi
    #             - downwardAPI
    #             - emptyDir
    #             - ephemeral
    #             - persistentVolumeClaim
    #             - projected
    #             - secret
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gha-ns-meta
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Namespace
                apiVersion: v1
                metadata:
                  name: arc-systems
                  annotations:
                    openshift.io/sa.scc.supplemental-groups: 0/165537
                    openshift.io/sa.scc.uid-range: 0/165537
    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: eso-vault-clustersecretstore
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gha-ext-secret
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: external-secrets.io/v1beta1
                kind: ExternalSecret
                metadata:
                  name: gha-controller
                  namespace: arc-systems
                spec:
                  refreshInterval: "3600s"
                  secretStoreRef:
                    name: kemo-labs-vault
                    kind: ClusterSecretStore
                  target:
                    name: kemo-labs-ocp-arc # name of the k8s Secret to make in this namespace
                    creationPolicy: Owner
                    deletionPolicy: Retain
                    template:
                      engineVersion: v2
                      type: Opaque # type of k8s Secret to make
                  data:
                    - secretKey: github_app_id
                      remoteRef:
                        key: external/github/arc # name of the secret under the target Vault path
                        property: github_app_id # # name of the key in that named Vault secret
                    - secretKey: github_app_installation_id
                      remoteRef:
                        key: external/github/arc # name of the secret under the target Vault path
                        property: github_app_installation_id # # name of the key in that named Vault secret
                    - secretKey: github_app_private_key
                      remoteRef:
                        key: external/github/arc # name of the secret under the target Vault path
                        property: github_app_private_key # # name of the key in that named Vault secret

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gha-rbac
        spec:
          remediationAction: enforce
          severity: low
          object-templates:

            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: arc-ss-init
                  namespace: arc-systems
                rules:
                  - apiGroups: [""]
                    resources: ["pods"]
                    verbs: ["get", "list", "create", "delete"]
                  - apiGroups: [""]
                    resources: ["pods/exec"]
                    verbs: ["get", "create"]
                  - apiGroups: [""]
                    resources: ["pods/log"]
                    verbs: ["get", "list", "watch"]
                  - apiGroups: ["batch"]
                    resources: ["jobs"]
                    verbs: ["get", "list", "create", "delete"]
                  - apiGroups: [""]
                    resources: ["secrets"]
                    verbs: ["create", "delete", "get", "list"]
            - complianceType: musthave
              objectDefinition:
                kind: RoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: gharc-ss-init
                  namespace: arc-systems
                subjects:
                  - kind: ServiceAccount
                    name: arc-gha-rs-controller
                    namespace: arc-systems
                  - kind: ServiceAccount
                    name: tri-force-gha-rs-no-permission
                    namespace: arc-systems
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: Role
                  name: 'arc-ss-init'

            - complianceType: musthave
              objectDefinition:
                apiVersion: security.openshift.io/v1
                kind: SecurityContextConstraints
                metadata:
                  annotations:
                    kubernetes.io/description: 'nested-container-arc is specially tailored for running nested containers for GitHub Actions Runner Controller. It balances a tight security profile, while remaining loose enough to be useful to run nested containers in. In addition to requiring pods run with a user namespace, it allows SETUID and SETGID capabilities, requires the "container_engine_t" SELinux type, allows any users within the range of 0-65534, allows privilege escalation (to allow a container engine to run new{uid/gid}map), and allows any seccomp profile. Since any pods running within this SCC must use a user namespace ("hostUsers: false"), their actual UID/GID on the host will be allocated by the kubelet to be unprivileged, and any capabilities the pod is granted will not apply outside of the pods user namespace.'
                  name: nested-container-arc
                userNamespaceLevel: RequirePodLevel
                allowPrivilegedContainer: true # true?
                allowPrivilegeEscalation: true
                allowHostPorts: false
                allowHostDirVolumePlugin: false
                allowHostIPC: false
                allowHostPID: false
                allowHostNetwork: false
                runAsUser:
                  type: MustRunAsRange
                  uidRangeMax: 65534
                  uidRangeMin: 0
                fsGroup:
                  ranges:
                    - max: 65534
                  type: MustRunAs
                supplementalGroups:
                  ranges:
                    - max: 65534
                  type: MustRunAs

                requiredDropCapabilities: null
                defaultAddCapabilities: null
                allowedCapabilities:
                  - SETUID
                  - SETGID
                  - SYS_ADMIN
                  - NET_ADMIN
                  - MKNOD

                seccompProfiles:
                  - '*'
                seLinuxContext:
                  seLinuxOptions:
                    type: container_engine_t
                  type: MustRunAs

                readOnlyRootFilesystem: false
                volumes:
                  - configMap
                  - csi
                  - downwardAPI
                  - emptyDir
                  - ephemeral
                  - image
                  - persistentVolumeClaim
                  - projected
                  - secret
                users: []
                groups: []
                priority: null

            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRole
                metadata:
                  name: system:openshift:scc:nested-container-arc
                rules:
                - apiGroups:
                  - security.openshift.io
                  resourceNames:
                  - nested-container-arc
                  resources:
                  - securitycontextconstraints
                  verbs:
                  - use

            - complianceType: musthave
              objectDefinition:
                kind: RoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: gharc-nested-container-arc
                  namespace: arc-systems
                subjects:
                  - kind: ServiceAccount
                    name: arc-gha-rs-controller
                    namespace: arc-systems
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: 'system:openshift:scc:nested-container-arc'
            # - complianceType: musthave
            #   objectDefinition:
            #     kind: RoleBinding
            #     apiVersion: rbac.authorization.k8s.io/v1
            #     metadata:
            #       name: gharc-userns
            #       namespace: arc-systems
            #     subjects:
            #       - kind: ServiceAccount
            #         name: arc-gha-rs-controller
            #         namespace: arc-systems
            #     roleRef:
            #       apiGroup: rbac.authorization.k8s.io
            #       kind: ClusterRole
            #       name: 'system:openshift:scc:github-arc'
