---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: hcp-bmh-console
  annotations:
    policy.open-cluster-management.io/description: Creates (most of) the things needed to automatically bring up the OpenShift Console for a Hosted Control Plane cluster using Bare Metal Workers
    policy.open-cluster-management.io/categories: OCPCM - OpenShift Configuration Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: CBC - Cluster Baseline Configuration
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: metallb-namespace
        spec:
          remediationAction: enforce
          severity: critical
          namespaceSelector:
            include:
              - metallb
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: metallb
                  annotations:
                    workload.openshift.io/allowed: management
          pruneObjectBehavior: None

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: metallb-operator-group
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: metallb-group
                  namespace: metallb
                spec:
                  upgradeStrategy: Default
          pruneObjectBehavior: None
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: metallb-subscription
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: metallb-operator
                  namespace: metallb
                spec:
                  channel: stable
                  installPlanApproval: Automatic
                  name: metallb-operator
                  source: redhat-operators 
                  sourceNamespace: openshift-marketplace

    # - objectDefinition:
    #     apiVersion: policy.open-cluster-management.io/v1beta1
    #     kind: OperatorPolicy
    #     metadata:
    #       name: install-metallb
    #     spec:
    #       remediationAction: enforce
    #       severity: critical
    #       complianceType: musthave
    #       subscription:
    #         name: metallb-operator
    #         namespace: metallb
    #         channel: stable
    #         source: redhat-operators
    #         sourceNamespace: openshift-marketplace
    #       upgradeApproval: Automatic
    #       pruneObjectBehavior: None
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-metallb-system
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            include:
              - metallb
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: metallb.io/v1beta1
                kind: MetalLB
                metadata:
                  name: metallb
                  namespace: metallb
                spec:
                  bgpBackend: frr
          pruneObjectBehavior: None
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-lb-service
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            include:
              - metallb
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Service
                apiVersion: v1
                metadata:
                  name: metallb-ingress
                  namespace: openshift-ingress
                spec:
                  ports:
                    - name: http
                      protocol: TCP
                      port: 80
                      targetPort: 80
                    - name: https
                      protocol: TCP
                      port: 443
                      targetPort: 443
                  selector:
                    ingresscontroller.operator.openshift.io/deployment-ingresscontroller: default
                  type: LoadBalancer
          pruneObjectBehavior: None