---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: health-mc-addons
  #namespace: open-cluster-management-policies
  annotations:
    policy.open-cluster-management.io/description: Raises policy violations for every unreachable addon
    policy.open-cluster-management.io/categories: O11Y - OpenShift Observability
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: CH - Cluster Health
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: ocm-feature-foo-test
        spec:
          remediationAction: inform
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
              - openshift-*
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1
                kind: ManagedCluster
                metadata:
                  labels:
                    feature.open-cluster-management.io/foo: unreachable
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: addon-governance-policy-framework
        spec:
          remediationAction: inform
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
              - openshift-*
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1
                kind: ManagedCluster
                metadata:
                  labels:
                    feature.open-cluster-management.io/addon-governance-policy-framework: unreachable
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: addon-application-manager
        spec:
          remediationAction: inform
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
              - openshift-*
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1
                kind: ManagedCluster
                metadata:
                  labels:
                    feature.open-cluster-management.io/addon-application-manager: unreachable
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: addon-managed-serviceaccount
        spec:
          remediationAction: inform
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
              - openshift-*
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1
                kind: ManagedCluster
                metadata:
                  labels:
                    feature.open-cluster-management.io/addon-managed-serviceaccount: unreachable
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: addon-search-collector
        spec:
          remediationAction: inform
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
              - openshift-*
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1
                kind: ManagedCluster
                metadata:
                  labels:
                    feature.open-cluster-management.io/addon-search-collector: unreachable
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: addon-observability-controller
        spec:
          remediationAction: inform
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
              - openshift-*
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1
                kind: ManagedCluster
                metadata:
                  labels:
                    feature.open-cluster-management.io/addon-observability-controller: unreachable
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: addon-cluster-proxy
        spec:
          remediationAction: inform
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
              - openshift-*
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1
                kind: ManagedCluster
                metadata:
                  labels:
                    feature.open-cluster-management.io/addon-cluster-proxy: unreachable
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: addon-config-policy-controller
        spec:
          remediationAction: inform
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
              - openshift-*
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1
                kind: ManagedCluster
                metadata:
                  labels:
                    feature.open-cluster-management.io/addon-config-policy-controller: unreachable
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: addon-cert-policy-controller
        spec:
          remediationAction: inform
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
              - openshift-*
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1
                kind: ManagedCluster
                metadata:
                  labels:
                    feature.open-cluster-management.io/addon-cert-policy-controller: unreachable
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: addon-work-manager
        spec:
          remediationAction: inform
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
              - openshift-*
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1
                kind: ManagedCluster
                metadata:
                  labels:
                    feature.open-cluster-management.io/addon-work-manager: unreachable
