# Shamelessly stolen from https://github.com/bry-tam/acm-policy-samples/blob/main/policies/cluster-health/clusterversion.yml
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: health-clusterversion
  #namespace: open-cluster-management-policies
  annotations:
    policy.open-cluster-management.io/description: Raises policy violations if the managed cluster is not in a healthy state based on ClusterVersion status.
    policy.open-cluster-management.io/categories: O11Y - OpenShift Observability
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: CH - Cluster Health
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cluster-version-status
        spec:
          remediationAction: inform
          severity: high
          object-templates-raw: |
            {{/* ##  Get the current or desired version of the cluster ## */}}
            {{- $cVer := (lookup "config.openshift.io/v1" "ClusterVersion" "" "version") }}
            {{- $desiredVersion := (dig "desiredUpdate" "version" ($cVer.status.desired.version) $cVer.spec) }}

            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: ClusterVersion
                metadata:
                  name: version
                status:
                  history:
                    - version: {{ $desiredVersion }}
                      state: "Completed"
                  conditions:
                    - status: 'True'
                      type: Available
                    - status: 'False'
                      type: Failing
                    - status: 'False'
                      type: Progressing