---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: instance-acs-central
  annotations:
    policy.open-cluster-management.io/description: Deploys the ACS Central instance
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-INST - Operator Instance
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: stackrox-central-consolelink
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: console.openshift.io/v1
                kind: ConsoleLink
                metadata:
                  name: rhacs-console-link
                spec:
                  applicationMenu:
                    imageURL: 'https://d7umqicpi7263.cloudfront.net/img/product/f27b2400-a8de-4e69-a7e0-96a7db12bed3/1e769715-a188-40fc-99eb-1b6439509773.png'
                    section: Red Hat applications
                  href: 'https://{{ (lookup "route.openshift.io/v1" "Route" "stackrox" "central").spec.host }}'
                  location: ApplicationMenu
                  text: Advanced Cluster Security
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: stackrox-central
        spec:
          remediationAction: enforce
          severity: critical
          namespaceSelector:
            include:
              - stackrox
          object-templates:
            - complianceType: musthave
              objectDefinition:
            - complianceType: musthave
              objectDefinition:
                # This lets us bootstrap the SecuredCluster instance policy allowing secrets to be created
                apiVersion: cluster.open-cluster-management.io/v1beta2
                kind: ManagedClusterSetBinding
                metadata:
                  name: global
                  namespace: stackrox
                spec:
                  clusterSet: global
            - complianceType: musthave
              objectDefinition:
                apiVersion: platform.stackrox.io/v1alpha1
                kind: Central
                metadata:
                  name: stackrox-central-services
                  namespace: stackrox
                spec:
                  configAsCode:
                    configAsCodeComponent: Enabled
                  monitoring:
                    openshift:
                      enabled: true
                  network:
                    policies: Enabled
                  central:
                    notifierSecretsEncryption:
                      enabled: false
                    exposure:
                      loadBalancer:
                        enabled: false
                        port: 443
                      nodePort:
                        enabled: false
                      route:
                        enabled: true
                        reencrypt:
                          enabled: false
                    telemetry:
                      enabled: true
                    db:
                      isEnabled: Default
                      connectionPoolSize:
                        maxConnections: 90
                        minConnections: 10
                      persistence:
                        persistentVolumeClaim:
                          claimName: central-db
                    persistence:
                      persistentVolumeClaim:
                        claimName: stackrox-db
                  egress:
                    connectivityPolicy: Online
                  scannerV4:
                    db:
                      persistence:
                        persistentVolumeClaim:
                          claimName: scanner-v4-db
                    indexer:
                      scaling:
                        autoScaling: Enabled
                        maxReplicas: 3
                        minReplicas: 1
                        replicas: 1
                    matcher:
                      scaling:
                        autoScaling: Enabled
                        maxReplicas: 3
                        minReplicas: 1
                        replicas: 1
