---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: instance-acs-central
  annotations:
    policy.open-cluster-management.io/description: Deploys the ACS Central instance
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-INST - Operator Instance
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: stackrox-central
        spec:
          remediationAction: enforce
          severity: critical
          namespaceSelector:
            include:
              - stackrox
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: platform.stackrox.io/v1alpha1
                kind: Central
                metadata:
                  name: stackrox-central-services
                  namespace: stackrox
                spec:
                  configAsCode:
                    configAsCodeComponent: Enabled
                  monitoring:
                    openshift:
                      enabled: true
                  network:
                    policies: Enabled
                  central:
                    notifierSecretsEncryption:
                      enabled: false
                    exposure:
                      loadBalancer:
                        enabled: false
                        port: 443
                      nodePort:
                        enabled: false
                      route:
                        enabled: true
                        reencrypt:
                          enabled: false
                    telemetry:
                      enabled: true
                    db:
                      isEnabled: Default
                      connectionPoolSize:
                        maxConnections: 90
                        minConnections: 10
                      persistence:
                        persistentVolumeClaim:
                          claimName: central-db
                    persistence:
                      persistentVolumeClaim:
                        claimName: stackrox-db
                  egress:
                    connectivityPolicy: Online
                  scannerV4:
                    db:
                      persistence:
                        persistentVolumeClaim:
                          claimName: scanner-v4-db
                    indexer:
                      scaling:
                        autoScaling: Enabled
                        maxReplicas: 3
                        minReplicas: 1
                        replicas: 1
                    matcher:
                      scaling:
                        autoScaling: Enabled
                        maxReplicas: 3
                        minReplicas: 1
                        replicas: 1
