---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-policies

resources:
  - namespace.yaml
  - global-base-namespaces.yaml
  - root-ca.yaml

  # Hub things
  - managed-mcsb/

  # Health Signals
  - health-checks/

  # Global/Common Policies
  - maintenance/
  - capabilities/
  - compliance/
  - composition/
  # - best-practices/
  - audit-logging-config.yaml
  - compliance-scan-cis.yaml
  - compliance-scan-e8.yaml
  - configure-idp.yaml
  - configure-ingress-certs.yaml
  - configure-project-template.yaml
  - console-info-header.yaml
  - default-gatewayclass.yaml
  - disable-self-provisioner.yaml
  - enable-hcp.yaml
  - enable-internal-registry.yaml
  - enable-multinetworkpolicy.yaml
  - encrypt-etcd.yaml
  - hcp-bmh-infra-creds.yaml
  - image-vuln-scanning.yaml
  - increase-fd-limits.yaml
  - label-nodes-egressip.yaml
  - openshift-samples-config.yaml
  - remove-kubeadmin.yaml
  - root-ca-distribution.yaml

  # Operator Installation Policies
  - versioned-operators/
  - operators/

  # Operator instances
  - operator-instances/
  - versioned-operator-instances/

  # RHACM Hub Policies
  #- hub-ocp-update-svc.yaml
  - hub-configure-acm-search.yaml

  # Hosted Control Plane, Bare Metal Policies
  - hcp-bmh-console.yaml

  # Hosted Control Plane, KubeVirt Policies

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true