---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: kyverno-outbound-proxy
  annotations:
    policy.open-cluster-management.io/description: Configures certain workloads to automatically work with a proxy.
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/categories: OCPKG - OpenShift Kyverno Governance
    policy.open-cluster-management.io/controls: CP-CFG - ClusterPolicy - Configuration
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: kyverno-outbound-proxy
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: kyverno.io/v1
                kind: ClusterPolicy
                metadata:
                  name: add-pod-proxies
                  annotations:
                    policies.kyverno.io/title: Add Pod Proxies
                    policies.kyverno.io/subject: Pod
                    policies.kyverno.io/category: Sample
                    policies.kyverno.io/minversion: 1.6.0
                    policies.kyverno.io/description: >-
                      In restricted environments, Pods may not be allowed to egress directly to all destinations
                      and some overrides to specific addresses may need to go through a corporate proxy.
                      This policy adds proxy information to Pods in the form of environment variables.
                      It will add the `env` array if not present. If any Pods have any of these
                      env vars, they will be overwritten with the value(s) in this policy.
                spec:
                  rules:
                  - name: add-pod-primary-proxies
                    match:
                      any:
                        - resources:
                            kinds:
                              - Pod # Pod will apply to its owners as well
                              #- Deployment # Just for Deployments instead of all Pod controllers
                            operations:
                            # Don't need to match on DELETE eh?
                              - CREATE
                              - UPDATE
                            # Only match Namespaces with the label "outbound-proxy=enabled"
                            # This is a good way to scope the policy to only certain namespaces
                            # and not all namespaces in the cluster.
                            namespaceSelector:
                              matchExpressions:
                                - key: outbound-proxy
                                  operator: In
                                  values:
                                  - enabled
                                  - primary
                            # Only match Pods with the label "app=critical"
                            # This is a good way to scope the policy to only certain Pods
                            # and not all Pods in the namespace/cluster.
                            selector:
                              matchLabels:
                                flag.proxy: enabled
                    mutate:
                      patchStrategicMerge:
                        spec:
                          containers:
                            - (name): "*"
                              env:
                              - name: HTTP_PROXY
                                value: http://proxy.kemo.labs:3129
                              - name: HTTPS_PROXY
                                value: http://proxy.kemo.labs:3129
                              - name: NO_PROXY
                                value: '.kemo.labs,.kemo.network,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,localhost,127.0.0.1,.svc,.local'

                  - name: add-pod-secondary-proxies
                    match:
                      any:
                        - resources:
                            kinds:
                              - Pod # Pod will apply to its owners as well
                              #- Deployment # Just for Deployments instead of all Pod controllers
                            operations:
                            # Don't need to match on DELETE eh?
                              - CREATE
                              - UPDATE
                            # Only match Namespaces with the label "outbound-proxy=enabled"
                            # This is a good way to scope the policy to only certain namespaces
                            # and not all namespaces in the cluster.
                            namespaceSelector:
                              matchExpressions:
                                - key: outbound-proxy
                                  operator: In
                                  values:
                                  - secondary
                            # Only match Pods with the label "app=critical"
                            # This is a good way to scope the policy to only certain Pods
                            # and not all Pods in the namespace/cluster.
                            selector:
                              matchLabels:
                                flag.proxy: enabled
                    mutate:
                      patchStrategicMerge:
                        spec:
                          containers:
                            - (name): "*"
                              env:
                                - name: HTTP_PROXY
                                  value: http://proxy.kemo.labs:3128
                                - name: HTTPS_PROXY
                                  value: http://proxy.kemo.labs:3128
                                - name: NO_PROXY
                                  value: '.kemo.labs,.kemo.network,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,localhost,127.0.0.1,.svc,.local'

                  - name: add-pod-secondary-proxies-ca-mnt
                    match:
                      any:
                        - resources:
                            kinds:
                              - Pod
                            operations:
                              - CREATE
                              - UPDATE
                            namespaceSelector:
                              matchExpressions:
                                - key: outbound-proxy
                                  operator: In
                                  values:
                                  - secondary
                            selector:
                              matchLabels:
                                attachProxyRootCA: enabled
                    mutate:
                      patchStrategicMerge:
                        spec:
                          volumes:
                            - name: out-prxy-root-ca
                              configMap:
                                name: out-prxy-root-ca
                                items:
                                  - key: ca-bundle.crt
                                    path: tls-ca-bundle.pem
                          containers:
                            - (name): "*"
                              volumeMounts:
                                - mountPath: /etc/pki/ca-trust/extracted/pem
                                  name: out-prxy-root-ca
                                  readOnly: true

                  - name: add-pod-secondary-proxies-ca
                    match:
                      any:
                        - resources:
                            kinds:
                              - Pod
                            operations:
                              - CREATE
                              - UPDATE
                            namespaceSelector:
                              matchExpressions:
                                - key: outbound-proxy
                                  operator: In
                                  values:
                                  - secondary
                            selector:
                              matchLabels:
                                attachProxyRootCA: enabled
                    generate:
                      synchronize: false
                      apiVersion: v1
                      kind: ConfigMap
                      name: out-prxy-root-ca
                      namespace: '{{ "{{ request.object.metadata.namespace }}" }}'
                      data:
                        kind: ConfigMap
                        metadata:
                          labels:
                            config.openshift.io/inject-trusted-cabundle: 'true'
                          data: {}