---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: operators-descheduler
  annotations:
    policy.open-cluster-management.io/description: Installs the Kube Descheduler Operator
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-SUB - Operator Installation
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: descheduler-namespace
        spec:
          remediationAction: enforce
          severity: critical
          namespaceSelector:
            include:
              - openshift-workload-availability
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-kube-descheduler-operator
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: descheduler-group
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: cluster-kube-descheduler-operator
                  namespace: openshift-kube-descheduler-operator
                spec:
                  upgradeStrategy: Default
                  targetNamespaces:
                    - openshift-kube-descheduler-operator
          pruneObjectBehavior: DeleteIfCreated
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: descheduler-subscription
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: cluster-kube-descheduler-operator
                  namespace: openshift-kube-descheduler-operator
                spec:
                  channel: stable
                  installPlanApproval: Automatic
                  name: cluster-kube-descheduler-operator
                  source: redhat-operators 
                  sourceNamespace: openshift-marketplace
