apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: operators-nvidia-gpu
  annotations:
    policy.open-cluster-management.io/description: Installs the NVIDIA GPU Operator
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-OI - Operator Installation
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: nvidia-gpu-namespace
        spec:
          remediationAction: enforce
          severity: critical
          namespaceSelector:
            include:
              - nvidia-gpu-operator
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: nvidia-gpu-operator
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: nvidia-gpu-operator-group
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: gpu-operator-certified-group
                  namespace: nvidia-gpu-operator
                spec:
                  targetNamespaces:
                    - nvidia-gpu-operator
                  upgradeStrategy: Default
          pruneObjectBehavior: DeleteIfCreated
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gpu-operator-certified-subscription
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: gpu-operator-certified
                  namespace: nvidia-gpu-operator
                spec:
                  channel: stable
                  installPlanApproval: Automatic
                  name: gpu-operator-certified
                  source: certified-operators 
                  sourceNamespace: openshift-marketplace
