apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: remove-kubeadmin
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/controls: SC-1 System and Communications Protection Policy and Procedures
spec:
  disabled: false
  policy-templates:
    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: oauth-configuration
          namespace: ""
          compliance: Compliant

      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: remove-kubeadmin
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                kind: Secret
                apiVersion: v1
                metadata:
                  name: kubeadmin
                  namespace: kube-system
                type: Opaque