apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: agent-managed-clusters
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  sourceNamespaces:
  - argocd-agent-managed-clusters