apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: argocd-agent
  namespace: argocd
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: argocd-agent-ca
  namespace: argocd
spec:
  ca:
    secretName: argocd-hub-agent-ca