apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - appproj.yaml
  - agent-service.yaml
  - agent-route.yaml
  - issuer.yaml

patches:
  - path: patch-agent.yaml
    target:
      kind: ArgoCD
