apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Template
      name: .*
    path: patch.yaml

commonLabels:
  flavor.template.kubevirt.io/small: 'true'
  workload.template.kubevirt.io/desktop: 'true'
