---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kenmoini/smart-drone-patterns/apps/simple-chat/deployment/overlays/persistent/?timeout=360&ref=main