---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: classification-banner
  #namespace: open-cluster-management-policies
  annotations:
    policy.open-cluster-management.io/categories: OCPCM - OpenShift Configuration Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: CBC - Cluster Baseline Configuration
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: classification-banner
        spec:
          remediationAction: enforce
          severity: critical
          pruneObjectBehavior: DeleteIfCreated
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: console.openshift.io/v1
                kind: ConsoleNotification
                metadata:
                  name: classification-banner
                spec:
                  backgroundColor: '#000'
                  color: '#FFF'
                  location: BannerTop
                  text: 'THIS IS TOTALLY A CLASSIFIED CLUSTER!  YUP!'
