---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: imagestream-sets-schedule
  annotations:
    policy.open-cluster-management.io/description: Ensures ImageStream sets are scheduled correctly
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: imagestream-sets-schedule
        spec:
          remediationAction: enforce
          severity: low
    # {{- if and (not $hasOwner) ($hasTags) (gt $tagLength 0) }}
          object-templates-raw: |
            {{/* ##  Loop through all the ImageStreams ## */}}
            {{- $imageStreamList := (lookup "image.openshift.io/v1" "ImageStream" "" "").items }}
            {{- range $imageStream := $imageStreamList }}
            {{- $hasOwner := (hasKey $imageStream.metadata "ownerReferences") }}
            {{- $tagLength := 0 }}
            {{- $hasTags := (hasKey $imageStream.spec "tags") }}
            {{- if eq $hasTags true }}
            {{- $tagLength := len $imageStream.spec.tags | default 0 }}
            {{- end }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: image.openshift.io/v1
                kind: ImageStream
                metadata:
                  name: {{ $imageStream.metadata.name }}
                  namespace: {{ $imageStream.metadata.namespace }}
                  labels:
                    policy.kemo.dev/managed-by: imagestream-sets-schedule
                    numTags: '{{ $tagLength }}'
                    hasTags: '{{ $hasTags }}'
                    hasOwner: '{{ $hasOwner }}'
            {{- end }}
        # spec:
        #   tags:
        #   {{- range $tag := $imageStream.spec.tags }}
        #   {{- if eq $tag.from.kind "DockerImage" }}
        #   - name: '{{ $tag.name }}'
        #     importPolicy:
        #       scheduled: true
        #   {{- end -}}
        #   {{- end -}}
            # {{- end }}