apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: kernelarg-vsyscall
  annotations:
    policy.open-cluster-management.io/categories: OCPC - OpenShift Compliance
    policy.open-cluster-management.io/standards: Kemo Labs 2026
    policy.open-cluster-management.io/controls: CR - Compliance Remediation
    compliance.openshift.io/rule: kernelarg-vsyscall
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: kernelarg-vsyscall
        spec:
          remediationAction: enforce
          severity: high
          pruneObjectBehavior: DeleteIfCreated
          object-templates:
          # rhcos4-high-master-coreos-vsyscall-kernel-argument
          # rhcos4-stig-master-coreos-vsyscall-kernel-argument
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: machineconfiguration.openshift.io/v1
                kind: MachineConfig
                metadata:
                  labels:
                    machineconfiguration.openshift.io/role: master
                  name: 75-master-kernelarg-vsyscall
                spec:
                  config:
                    ignition:
                      version: 3.1.0
                  kernelArguments:
                    - vsyscall=none
            - complianceType: mustonlyhave
          # rhcos4-high-worker-coreos-vsyscall-kernel-argument
          # rhcos4-stig-worker-coreos-vsyscall-kernel-argument
              objectDefinition:
                apiVersion: machineconfiguration.openshift.io/v1
                kind: MachineConfig
                metadata:
                  labels:
                    machineconfiguration.openshift.io/role: worker
                  name: 75-worker-kernelarg-vsyscall
                spec:
                  config:
                    ignition:
                      version: 3.1.0
                  kernelArguments:
                    - vsyscall=none