---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-policies

resources:
  - auditd-rules.yaml
  - check-fips.yaml
  - classification-banner.yaml
  - console-logout-redirect.yaml
  - disable-sshd.yaml
  - enable-usb-guard.yaml
  - imagestream-sets-schedule.yaml
  - kernelarg-audit.yaml
  - kernelarg-backlog-limit.yaml
  - kernelarg-page-poison.yaml
  - kernelarg-slub-debug.yaml
  - kernelarg-vsyscall.yaml
  - sysctls.yaml