---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: mcsb-global-rhdh
  annotations:
    policy.open-cluster-management.io/description: Creates a ManagedClusterSetBinding to the 'global' ManagedClusterSet in the 'rhdh' namespace.
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: ACM-CFG - Advanced Cluster Management Configuration
spec:
  disabled: false
  policy-templates:

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: mcsb-global-rhdh-check
        spec:
          remediationAction: inform
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: rhdh

    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: mcsb-global-rhdh-check
          namespace: ""
          compliance: Compliant
      ignorePending: true
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: mcsb-global-rhdh
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta2
                kind: ManagedClusterSetBinding
                metadata:
                  name: global
                  namespace: rhdh
                spec:
                  clusterSet: global