---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: instance-aap-2.6
  annotations:
    policy.open-cluster-management.io/description: Deploys the Ansible Automation Platform 2.6 instance
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-INST - Operator Instance
spec:
  disabled: false
  policy-templates:

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: aap-ca-bundle-secret
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                type: Opaque
                metadata:
                  name: aap-ca-bundle
                  namespace: aap
                data:
                  bundle-ca.crt: '{{ (fromConfigMap "open-cluster-management-policies" "root-ca-bundle" "ca-bundle.crt") | base64enc }}'
      extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: aap-operator-install-check
          namespace: ""
          compliance: Compliant

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: aap-hub-instance
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: aap.ansible.com/v1alpha1
                kind: AnsibleAutomationPlatform
                metadata:
                  name: hub
                  namespace: aap
                spec:
                  bundle_cacert_secret: aap-ca-bundle
                  api:
                    log_level: INFO
                    replicas: 1
                  database:
                    postgres_data_volume_init: false
                  ingress_type: Route
                  no_log: true
                  redis_mode: standalone
                  route_tls_termination_mechanism: Edge
                  service_type: ClusterIP
                  lightspeed:
                    disabled: true
                  hub:
                    disabled: false
                    file_storage_storage_class: ocs-storagecluster-cephfs
      extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: aap-ca-bundle-secret
          namespace: ""
          compliance: Compliant

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: aap-hub-route-check
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: route.openshift.io/v1
                kind: Route
                metadata:
                  namespace: aap
                  name: hub
      extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: aap-hub-instance
          namespace: ""
          compliance: Compliant


    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: aap-consolelink
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: console.openshift.io/v1
                kind: ConsoleLink
                metadata:
                  name: aap-console-link
                spec:
                  applicationMenu:
                    imageURL: 'https://www.redhat.com/rhdc/managed-files/ansible-automation-platform-200.svg'
                    section: Red Hat applications
                  href: 'https://{{ (lookup "route.openshift.io/v1" "Route" "aap" "hub").spec.host }}'
                  location: ApplicationMenu
                  text: Ansible Automation Platform
      extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: aap-instance-route-check
          namespace: ""
          compliance: Compliant