---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: instance-acs-secured-cluster
  annotations:
    policy.open-cluster-management.io/description: Deploys the ACS Secured Cluster instance
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-INST - Operator Instance
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: stackrox-secured-cluster
        spec:
          remediationAction: enforce
          severity: critical
          namespaceSelector:
            include:
              - stackrox
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: platform.stackrox.io/v1alpha1
                kind: SecuredCluster
                metadata:
                  name: stackrox-secured-cluster-services
                  namespace: stackrox
                spec:
                  scannerV4:
                    db:
                      persistence:
                        persistentVolumeClaim:
                          claimName: scanner-v4-db
                    indexer:
                      scaling:
                        autoScaling: Enabled
                        maxReplicas: 3
                        minReplicas: 1
                        replicas: 1
                    scannerComponent: AutoSense
                  clusterName: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "stackrox" "cluster").status.infrastructureName }}'
                  centralEndpoint: '{{hub (lookup "route.openshift.io/v1" "Route" "stackrox" "central").spec.host hub}}:443'
                  perNode:
                    collector:
                      #collection: EBPF
                      collection: CORE_BPF
                      imageFlavor: Regular
                    taintToleration: TolerateTaints
                  monitoring:
                    openshift:
                      enabled: true
                  auditLogs:
                    collection: Auto
                  admissionControl:
                    listenOnUpdates: true
                    bypass: BreakGlassAnnotation
                    contactImageScanners: DoNotScanInline
                    listenOnCreates: true
                    timeoutSeconds: 20
                    listenOnEvents: true
                  tls:
                    additionalCAs:
                      - content: |
                          -----BEGIN CERTIFICATE-----
                          MIIGqzCCBJOgAwIBAgIUKMZCYZxHomZOUFLz8j0/ItBY/3cwDQYJKoZIhvcNAQEL
                          BQAwgdwxKzApBgkqhkiG9w0BCQEWHGNlcnRtYXN0ZXJAcG9seWdsb3QudmVudHVy
                          ZXMxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQMA4GA1UE
                          BwwHUmFsZWlnaDEaMBgGA1UECgwRUG9seWdsb3QgVmVudHVyZXMxIjAgBgNVBAsM
                          GVBvbHlnbG90IFZlbnR1cmVzIEluZm9TZWMxNTAzBgNVBAMMLFBvbHlnbG90IFZl
                          bnR1cmVzIFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTIxMTEyODIyMTE1
                          MVoXDTQyMDYxMTIyMTE1MVowgdwxKzApBgkqhkiG9w0BCQEWHGNlcnRtYXN0ZXJA
                          cG9seWdsb3QudmVudHVyZXMxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBD
                          YXJvbGluYTEQMA4GA1UEBwwHUmFsZWlnaDEaMBgGA1UECgwRUG9seWdsb3QgVmVu
                          dHVyZXMxIjAgBgNVBAsMGVBvbHlnbG90IFZlbnR1cmVzIEluZm9TZWMxNTAzBgNV
                          BAMMLFBvbHlnbG90IFZlbnR1cmVzIFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
                          MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAp6gp+cohBjNjCfQYaHyl
                          3OChI32xFkU+S68cP27cG9GS6+GfOkmnxavVa8HfYKIYDYwLvev22DrF+ErkL+sq
                          KO1c0cJd2jT0sf6snHhT3k0kS+uthscL4ZMHh6ux2ULhR0n9JPrAwGlSLZZpIph8
                          clZU8JkLipVdhwAUpHEvcyxkk+e/tWiz1ir6uhI17WifFu+nDZiyjWtLqmRVWhnQ
                          0ngTgcP2WwlRBrlSvaBfXYoFEZSwajGhoaKoJJ2pRcrzhz0ImmEykiqw+7cBXCw+
                          9926rxqNtDVGC7P/f9pcks90JH+bg+PFPcgdHT5fGXHJct54bvvPLDMLPAjPUS0d
                          NhCqF1EfLhI+1wbtuijMlfjyBdy9Mz6f5PmKvE2OcmvBm1EwoKJRJ5OY4d6U94L4
                          ljLotCuLwCmRAO/wvIMxo0AM/yu86HuMgytE0SOhzXBL8GHjubfFpTOV5K6wFR/d
                          YOOxKmGGftAH0rh/GyWRdQuGwy+XaFFMN3uU0v26dJw1qzFlObKD8D9h20Po8LxH
                          dngQZvK0XwKb/rtG5ti7sMrm00kGeFilZqo4ZcJayCP9PRf7VTkBPa8lSaiq/Xgi
                          aYBnnJ19wtWgupy+96yzf0Vv+lCpo1Q/ItND2mfvJ32Ec/WoytYE7ZGHiTzAQ7tB
                          WFpwiqeC2u9cIbWYGPjY+JcCAwEAAaNjMGEwHQYDVR0OBBYEFAMrzv+9iNPU+QIl
                          8QKZmWrXicOlMB8GA1UdIwQYMBaAFAMrzv+9iNPU+QIl8QKZmWrXicOlMA8GA1Ud
                          EwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGGMA0GCSqGSIb3DQEBCwUAA4ICAQAG
                          cUG6p0q9ixjdfLwA75xfyrPbaTx3jAkVnCtre5GQV1j0IfGpfaGxzqb7zVHHfRkN
                          LklrFQZRrnsraBGpCKLZCCJ93UTglTbRAcAwHr7C0vodikVe8VZUAcAonMS1VE0Q
                          qC3tma56ddOog1nSRbqCQ8/Y7GJM6ZxbFs9TT7/ld4jCqBhXQeIRXKwlRZi2KVLm
                          xdSVp5VWMrmFyvw2QGkj1evkheQREbDRaXhZ95NkhTQIVDFbKzSSVYaEV/Nh1ZUC
                          7h7QiTWkULvsffjmYR/x2ifWBWb9jinM7Rl8hcJg4TvZz6qZuTWpPsA23huBbXor
                          6mmpSL8sbeXKawfUESYYc37HJ2n2WQOJ0hFoDFpK2nZnn4T+OWgNsGvwtPA6tfrZ
                          dXDCFKJDXlQIAZw+x9S5V1dr4AT1RShjrfD9gnimu0UxT9LvYmOLW1MjpycV5Zg9
                          coRfdfOXmGZm7R22i47pXAju8byHodatBlhRgFiUpwTuUoueElosgXkui9HzkfXx
                          tqUuc3dAaVH3vmeQpYb+LJ1wCn2mtnpJedui2N5dsqEQ1XsXjxp2bfWdhh52ZwHs
                          LSMk1f3L54UjG+iMyolALyCvpibGD6g6PRMp8UTStZatPJDzT2/JbFu9mIhU5V4g
                          zYML3t12ZU8JGpxxfUk2ObjKbixfSwSmTcWb+s8kgg==
                          -----END CERTIFICATE-----
                        name: pgv-ca-bundle.crt
                      - content: |
                          -----BEGIN CERTIFICATE-----
                          MIIDGzCCAgOgAwIBAgIQIiia9v4QpyL2ar7kW4K2cDANBgkqhkiG9w0BAQsFADAm
                          MSQwIgYDVQQDExtLZW1vIExhYnMgU21hbGxTdGVwIFJvb3QgQ0EwHhcNMjIwNDAz
                          MjAzNDA5WhcNMzIwMzMxMjAzNDA5WjAmMSQwIgYDVQQDExtLZW1vIExhYnMgU21h
                          bGxTdGVwIFJvb3QgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDF
                          w9Y9/ScdF8bmgElmQQQFJku033PkOMtPOCakAaPCly1reqHm8r3Mjhjuqi8HiC94
                          NQ+jWYRFzAGyMUZfR9PaCnN4EsVRjX1KAvttX4eRXgAo8SsIb9ExKHVSVDoBCm62
                          /FpVYE24bgUcN5gqnp7lMdSlW69ArnpSnLOkQCGDXknSEBCGUdpz8jdehqAyXoFo
                          yedC9oAxvisEQ3SjyMQDqKo7XNS2VEODozGp0bNcym5461VHeIVulo1/8/kPfEkv
                          Zjr7ZzGjRiEn1a0wrbDtdTG5VSobGQW/I9VIgbXp0pTUUzurIAlOh+LzvnNwVKIv
                          XFkJfutEGrAxFDYX6K9xAgMBAAGjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMB
                          Af8ECDAGAQH/AgEBMB0GA1UdDgQWBBSuSpXt1rL5wa2CyYFfchCD3ZCzSjANBgkq
                          hkiG9w0BAQsFAAOCAQEAe6Prprq70SLis/5LJVl8pC+MgPa/ICukJ1O3C6Jn4w6y
                          GGCBwa26SAw49J54qizQPbQdks0px0fQCIzbKlVA44lfq6VwSpXrM/VgesGB4vez
                          vfdDBvJwnc5/E93NxtxinbVvNps7xfa2kW22xu2GZoOueAJr3gcG8ZQMZc7oMY4a
                          7OaqWH9OyUhax2Odv+37Its5PjBbr7vHabzw6F6849Lx1vDwlpg0dqCFVMSKvm4l
                          KK4oFUbZw0+cLmAlOYHrw5QIHqAGT7p8Cew5zR/fuuKJx2yiKP/tsz6E1OMejN9q
                          g/IdSjffp7OClDHFa3nuXzsKk87O3eTr4fzKALVpqQ==
                          -----END CERTIFICATE-----
                        name: klstep-ca-bundle.crt
                      - content: |
                          -----BEGIN CERTIFICATE-----
                          MIIG3TCCBMWgAwIBAgIUJSmf6Ooxg8uIwfFlHQYFQl5KMSYwDQYJKoZIhvcNAQEL
                          BQAwgcMxIzAhBgkqhkiG9w0BCQEWFG5hLXNlLXJ0b0ByZWRoYXQuY29tMQswCQYD
                          VQQGEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExEDAOBgNVBAcMB1JhbGVp
                          Z2gxFDASBgNVBAoMC05vdCBSZWQgSGF0MRswGQYDVQQLDBJTRSBSVE8gTm90IElu
                          Zm9TZWMxMTAvBgNVBAMMKFNvdXRoZWFzdCBSVE8gUm9vdCBDZXJ0aWZpY2F0ZSBB
                          dXRob3JpdHkwHhcNMjIwMzA3MDAwNTA5WhcNNDIwOTE4MDAwNTA5WjCBwzEjMCEG
                          CSqGSIb3DQEJARYUbmEtc2UtcnRvQHJlZGhhdC5jb20xCzAJBgNVBAYTAlVTMRcw
                          FQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQMA4GA1UEBwwHUmFsZWlnaDEUMBIGA1UE
                          CgwLTm90IFJlZCBIYXQxGzAZBgNVBAsMElNFIFJUTyBOb3QgSW5mb1NlYzExMC8G
                          A1UEAwwoU291dGhlYXN0IFJUTyBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eTCC
                          AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANGozAIcO/PB4uIwI31kuiGW
                          j+Nm+ZJruiOaG0P/Z99F/i7e9aOrQD8BHmlGOp9R0sdabrmidvowLE69g5z4+Q0E
                          4+Uvt4GX/DYOBVR/xuV3E8LFJN1zXXbFtXJlSBz3PLWNaySAcg55a/Pwz68EWFA1
                          H2RL5I/sPDpFiz0POnZ+MJ15BCQ2P5YCN7lsHSkmbRonz349WAhvE5OM6qIrBw/J
                          Y6AJtAuEVnyiKoilqEvg0Gz6mSnog2yJY1CktMmP7S6/DPuJpTrw74027mp+g1Pm
                          hRf8jVNsLNM7VPMo8AIodTCIc+Gv3EJ1bjMc/nF1F3K5jBQZrfe21QpgMKyeY/RV
                          FvoHaCy2Miw2RFE9HOo0rwnOohiXlZM6ZSL5AUfDH2tSlJJNr08fE4op48UMIahz
                          2My117CKFE2gRe5bhEEJAO9gOqsq1oOT4Oi3TP+lysjAVAIcnNFhQ1uRmJ93Y8HU
                          qOCOgH+PV7N+kNtOwy8y32+Czh6njL09IbR8TNH2fOXYVt7JDZjnfU+FdzagNWc5
                          C+aQCdpKIMig5OuU81Ac8k6+Aj0CBawOcBI63oxV/GWkUJPgQytmyo/2zswD9FcD
                          yIVL1nvJOwVWNEyOLtDWmEzSda6CVLFFQnAw35qgS94Hc7IS3nQW6XFEGj7xzTmd
                          b2xoEKhgx+dPw5h7AYPHAgMBAAGjgcYwgcMwHQYDVR0OBBYEFDzw4uwWVqsqJDNM
                          2Rz+ztC/ZgUNMB8GA1UdIwQYMBaAFDzw4uwWVqsqJDNM2Rz+ztC/ZgUNMA8GA1Ud
                          EwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGGMGAGA1UdHwRZMFcwVaBToFGGT2h0
                          dHBzOi8vcmVkLWhhdC1zZS1ydG8uZ2l0aHViLmlvOjQ0My9jcmxzL3NlLXJ0by1y
                          b290LWNlcnRpZmljYXRlLWF1dGhvcml0eS5jcmwwDQYJKoZIhvcNAQELBQADggIB
                          AFu7g/6ghP0PaLsjjAPW+QWqv9tMk8w0MKbKgVeUOX5xz1I7Svc1ndi2dMcYwK8W
                          pgF4bVR8T17NE3V0/xy6BGktN9BtErI9guk3zb3GBIx/1b3Mgce7134nGvhi4ik7
                          ziNB2WYwOgwxEpSA1eS68WNMT6pWZvosEZu9AKMUQ8ULsfxiKwVT+Pj171JxIvDV
                          blhilnOrBap7sP1XwS9OPcQhm0AMtFEj/zhadO1h2ynwKjd/VE2/nskfLvm1dXK5
                          DtdHsCdtT/hJ0XQjLkwOkl87WHZsy4u6kxQzxKH+LDWfSOCOksYD86fBdfQC66gL
                          7yJpX9BznEaGCKgFam3m42eH9msCIV/JTTLUbsrwzaEhxBLtpUeo6j1xF2khF8Ri
                          45Sir0yotZE0i72S4TLllkgQx9AaOiRAWvtYkcP1TBJnzL5viac3pkTnPjLiQ9BO
                          V8+9Y1O6wU0KTbLdMaz+Wfpti1lcnphQDsMJoGTe6wl3QpAK2jz32aFMoTkoyDK5
                          MwQqiTMkyOkPCiY4Rq1RRnYGIU7Ob125IjaFqyLvG9KWuiFsH7yn2nVH5kwy7O75
                          7yx0UiBuGVfG66I09YM1jR9nq7mKv30Sq1Fa/X76XyxDBGk0rLRCw02Ziq0rS8WG
                          S5kIfhw8FM52x6RHCwRicArO8HSTCf4ueEkFL7yj5xSI
                          -----END CERTIFICATE-----
                        name: serto-ca-bundle.crt
                      - name: kl-n-r-ca
                        content: |
                          -----BEGIN CERTIFICATE-----
                          MIIH0DCCBbigAwIBAgIUVgbrSwOVQdQJrxeN2XcYdCPyFEMwDQYJKoZIhvcNAQEL
                          BQAwgbQxHzAdBgkqhkiG9w0BCQEWEGtlbkBrZW5tb2luaS5jb20xCzAJBgNVBAYT
                          AlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQMA4GA1UEBwwHUmFsZWlnaDEW
                          MBQGA1UECgwNS2VtbyBWZW50dXJlczESMBAGA1UECwwJS2VtbyBMYWJzMS0wKwYD
                          VQQDDCRLZW1vIExhYnMgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMjUw
                          MTE5MTIwODMxWhcNNDUwODAyMTIwODMxWjCBtDEfMB0GCSqGSIb3DQEJARYQa2Vu
                          QGtlbm1vaW5pLmNvbTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9s
                          aW5hMRAwDgYDVQQHDAdSYWxlaWdoMRYwFAYDVQQKDA1LZW1vIFZlbnR1cmVzMRIw
                          EAYDVQQLDAlLZW1vIExhYnMxLTArBgNVBAMMJEtlbW8gTGFicyBSb290IENlcnRp
                          ZmljYXRlIEF1dGhvcml0eTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
                          ALIsyqUqJ3Cw2JjRIFDimTLbpsBtWHyFni6yx4epiOzSuotmdrJL0F/PvvpTP1Lh
                          gPls09AO0GWHBIvnfThUZ0x8SKiL0f27b9rJULHdiVOqBMAOc2i6M83DMYsMXCS3
                          tPtpTXZkcQlCWAW53omB1po5Gg/H84aIO4zrvtSeWvvqlMrcbaFtN4NyFLtw16rc
                          yL60jGjUf0W2eXlRrJpQH5IG3JkI8wpFYB9U0Aj91vt2kSkPP68wGDIr/RF1uM0+
                          5YinRfEb8Ex0QY1FFPJL8elTgjHtuXVdqepoOaWXGcjy5WyV9FVX2R1OjNmhFmWI
                          Ev1Uejx+6Af7eR4mJvHgJWKGWZbxdjygih2AWXHR5n+k4RRc2cucMbGmQKQ3E66Y
                          twzQeUfzKkIZ1OMOKXlggh3eni+dSZ8ifkW78mNSJIAc+3iOCjlCLLXG8586JoMm
                          AJpH4LCY7GUP6upAq+V/bV4iuFy0mLYVeVFqjumCkd2wEwq2RB669tYeYdJJGX+G
                          pNOvXgw2SdZdb4tg/1pBQoKbse56sDeMz1F72AgR/28ahHzfgwZUCY2Gvmq5+Pbs
                          op8YHcTr52KN5haRjSLsfflFWTVhXl6t9D16bHGdMKp65IW20igFRMAR12vMvk1R
                          cveMukSNP5rHZG7KY7jUQwy+n6MZZMrGdxQcWt8xgdfNAgMBAAGjggHWMIIB0jAd
                          BgNVHQ4EFgQUVOlmpWXIqIG+cXDNOBAUN0VqAHEwgfQGA1UdIwSB7DCB6YAUVOlm
                          pWXIqIG+cXDNOBAUN0VqAHGhgbqkgbcwgbQxHzAdBgkqhkiG9w0BCQEWEGtlbkBr
                          ZW5tb2luaS5jb20xCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGlu
                          YTEQMA4GA1UEBwwHUmFsZWlnaDEWMBQGA1UECgwNS2VtbyBWZW50dXJlczESMBAG
                          A1UECwwJS2VtbyBMYWJzMS0wKwYDVQQDDCRLZW1vIExhYnMgUm9vdCBDZXJ0aWZp
                          Y2F0ZSBBdXRob3JpdHmCFFYG60sDlUHUCa8Xjdl3GHQj8hRDMA8GA1UdEwEB/wQF
                          MAMBAf8wDgYDVR0PAQH/BAQDAgGGMDUGCWCGSAGG+EIBDQQoFiZQaWthIFBLSSBH
                          ZW5lcmF0ZWQgUm9vdCBDQSBDZXJ0aWZpY2F0ZTBiBgNVHR8EWzBZMFegVaBThlFo
                          dHRwOi8vcGtpLmtlbW8ubmV0d29yay9wdWIvY3Jscy9yb290LWNhLmtlbW8tbGFi
                          cy1yb290LWNlcnRpZmljYXRlLWF1dGhvcml0eS5jcmwwDQYJKoZIhvcNAQELBQAD
                          ggIBABnSQENMmzNScyne0hxlArIR6mcQVtFO93kB8UMmXlpfy504Ds8lJSYGtP+g
                          51DTVSJxhfgcKkG0p/fOIs8EvwSlvZDWrWZyBifUEy563Hsaiq6rMU4R85E+Cr1W
                          dv7hYOUP7IIwEt2Gn4IulxAxRzkDyv7P74k8Y+9pjKi3BqxBa+U62WDqw160j8cy
                          K8QYGvyE/TkRvTi7FaM5ppr/0nNZ/7ZQ/pEEWTt60RpcXXFISSQ0tiJBUhOBxR2u
                          CMGB47vMRKrlmoVl6wDmhg6ItK3MWIntnXeGMvCSkRjVoa+N99JqpbbdF5+pxWKN
                          APl/fJqDgDAC5lmaiNu9o9nml84M1akB4G14GnLRyxUS4kraJajoyCq2bF2hgmoR
                          +m7y4hEPlsM8f4O++rleeg44gaMuaDTCdTGoNZ8piz9j+Mr5jiDOoApD/EFWWQ/I
                          G6kQYhL0cirA2VhtAVVCB8hhGLhv9A0tYO+xhcFmzMaIgKW1SdbZVgLIW2giYEjs
                          ftaT7oMpN7bO3CNFDJYA8+o94MO2pznlo390+eunOCLsq6691GzSPXZXPnCCyOQd
                          ATcP+OXC+Xljxsqpksht1DVnwjnmEZALd7T7crzCS/ezuqTtrVbUlsneIaNBhbpO
                          +wb3mZG781YXVp+JEbeksqL0Dstv6ldNQzawvAL6K7apTiJp
                          -----END CERTIFICATE-----


    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: stackrox-secured-cluster-secrets
        spec:
          remediationAction: enforce
          severity: critical
          namespaceSelector:
            include:
              - stackrox
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                type: Opaque
                metadata:
                  annotations:
                    init-bundle.stackrox.io/created-at: '{{hub index (lookup "v1" "Secret" "stackrox" "sensor-tls").metadata.annotations "init-bundle.stackrox.io/created-at" hub}}'
                    init-bundle.stackrox.io/expires-at: '{{hub index (lookup "v1" "Secret" "stackrox" "sensor-tls").metadata.annotations "init-bundle.stackrox.io/expires-at" hub}}'
                    init-bundle.stackrox.io/id: '{{hub index (lookup "v1" "Secret" "stackrox" "sensor-tls").metadata.annotations "init-bundle.stackrox.io/id" hub}}'
                    init-bundle.stackrox.io/name: '{{hub index (lookup "v1" "Secret" "stackrox" "sensor-tls").metadata.annotations "init-bundle.stackrox.io/name" hub}}'
                  name: sensor-tls
                  namespace: stackrox
                data:
                  ca.pem: '{{hub fromSecret "stackrox" "sensor-tls" "ca.pem" hub}}'
                  sensor-cert.pem: '{{hub fromSecret "stackrox" "sensor-tls" "sensor-cert.pem" hub}}'
                  sensor-key.pem: '{{hub fromSecret "stackrox" "sensor-tls" "sensor-key.pem" hub}}'

            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                type: Opaque
                metadata:
                  annotations:
                    init-bundle.stackrox.io/created-at: '{{hub index (lookup "v1" "Secret" "stackrox" "admission-control-tls").metadata.annotations "init-bundle.stackrox.io/created-at" hub}}'
                    init-bundle.stackrox.io/expires-at: '{{hub index (lookup "v1" "Secret" "stackrox" "admission-control-tls").metadata.annotations "init-bundle.stackrox.io/expires-at" hub}}'
                    init-bundle.stackrox.io/id: '{{hub index (lookup "v1" "Secret" "stackrox" "admission-control-tls").metadata.annotations "init-bundle.stackrox.io/id" hub}}'
                    init-bundle.stackrox.io/name: '{{hub index (lookup "v1" "Secret" "stackrox" "admission-control-tls").metadata.annotations "init-bundle.stackrox.io/name" hub}}'
                  name: admission-control-tls
                  namespace: stackrox
                data:
                  admission-control-cert.pem: '{{hub fromSecret "stackrox" "admission-control-tls" "admission-control-cert.pem" hub}}'
                  admission-control-key.pem: '{{hub fromSecret "stackrox" "admission-control-tls" "admission-control-key.pem" hub}}'
                  ca.pem: '{{hub fromSecret "stackrox" "admission-control-tls" "ca.pem" hub}}'

            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                type: Opaque
                metadata:
                  annotations:
                    init-bundle.stackrox.io/created-at: '{{hub index (lookup "v1" "Secret" "stackrox" "collector-tls").metadata.annotations "init-bundle.stackrox.io/created-at" hub}}'
                    init-bundle.stackrox.io/expires-at: '{{hub index (lookup "v1" "Secret" "stackrox" "collector-tls").metadata.annotations "init-bundle.stackrox.io/expires-at" hub}}'
                    init-bundle.stackrox.io/id: '{{hub index (lookup "v1" "Secret" "stackrox" "collector-tls").metadata.annotations "init-bundle.stackrox.io/id" hub}}'
                    init-bundle.stackrox.io/name: '{{hub index (lookup "v1" "Secret" "stackrox" "collector-tls").metadata.annotations "init-bundle.stackrox.io/name" hub}}'
                  name: collector-tls
                  namespace: stackrox
                data:
                  ca.pem: '{{hub fromSecret "stackrox" "collector-tls" "ca.pem" hub}}'
                  collector-cert.pem: '{{hub fromSecret "stackrox" "collector-tls" "collector-cert.pem" hub}}'
                  collector-key.pem: '{{hub fromSecret "stackrox" "collector-tls" "collector-key.pem" hub}}'