---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: instance-jobset
  annotations:
    policy.open-cluster-management.io/description: Deploys the Red Hat JobSet Operator Instance
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-INST - Operator Instance
spec:
  disabled: false
  policy-templates:
    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: jobset-operator-status
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: jobset-instance
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: JobSetOperator
                apiVersion: operator.openshift.io/v1
                metadata:
                  name: cluster
                spec:
                  logLevel: Normal
                  managementState: Managed
                  operatorLogLevel: Normal
