---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: instance-serverless
  annotations:
    policy.open-cluster-management.io/description: Deploys the OpenShift Serverless KNative Eventing and Serving
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-INST - Operator Instance
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: serving-config
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.knative.dev/v1beta1
                kind: KnativeServing
                metadata:
                  name: knative-serving
                  namespace: knative-serving
