---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: instance-ocp-logging
  #namespace: open-cluster-management-policies
  annotations:
    policy.open-cluster-management.io/description: Installs the Red Hat OpenShift Logging Operator with the Loki Stack
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-SUB - Operator Installation
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rh-loki-obc
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: objectbucket.io/v1alpha1
                kind: ObjectBucketClaim
                metadata:
                  name: loki
                  namespace: openshift-logging
                spec:
                  additionalConfig:
                    bucketclass: noobaa-default-bucket-class
                  generateBucketName: loki
                  objectBucketName: obc-openshift-storage-loki
                  storageClassName: openshift-storage.noobaa.io

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: logging-cco-ui-plugin
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: observability.openshift.io/v1alpha1
                kind: UIPlugin
                metadata:
                  name: logging
                spec:
                  type: Logging
                  logging:
                    lokiStack:
                      name: logging-loki
                    logsLimit: 50
                    timeout: 30s
                    schema: otel
