---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: instance-quay
  annotations:
    policy.open-cluster-management.io/description: Deploys the Quay Operator Instance
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-INST - Operator Instance
spec:
  disabled: false
  policy-templates:

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: quay-instance-ns
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: quay
                  annotations:
                    openshift.io/cluster-monitoring: "true"
                    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"key":"node-role.kubernetes.io/infra","operator":"Exists","effect":"NoSchedule"}]'
                    openshift.io/node-selector: 'node-role.kubernetes.io/{{ hasNodesWithExactRoles "infra" | ternary "infra" "worker" }}='

    # DO NOT STORE LIKE THIS IF YOU CAN HELP IT
    # PULL THE SECRET FROM ESO LIKE COMMENTED OUT BELOWWWWW
    # - objectDefinition:
    #     apiVersion: policy.open-cluster-management.io/v1
    #     kind: ConfigurationPolicy
    #     metadata:
    #       name: quay-instance-config-secret
    #     spec:
    #       remediationAction: enforce
    #       severity: critical
    #       object-templates:
    #         - complianceType: musthave
    #           objectDefinition:
    #             apiVersion: v1
    #             kind: Secret
    #             metadata:
    #               name: quay-config
    #               namespace: quay
    #             stringData:
    #               config.yaml: |
    #                 AUTHENTICATION_TYPE: Database
    #                 ALLOW_PULLS_WITHOUT_STRICT_LOGGING: true
    #                 ENTERPRISE_LOGO_URL: /static/img/RH_Logo_Quay_Black_UX-horizontal.svg
    #                 FEATURE_BUILD_SUPPORT: false
    #                 FEATURE_DIRECT_LOGIN: true
    #                 FEATURE_MAILING: false
    #                 FEATURE_UI_V2: true
    #                 FEATURE_UI_V2_REPO_SETTINGS: true
    #                 FEATURE_AUTO_PRUNE: true
    #                 FEATURE_PROXY_CACHE: true
    #                 FEATURE_QUOTA_MANAGEMENT: true
    #                 FEATURE_USER_INITIALIZE: true
    #                 FEATURE_APP_SPECIFIC_TOKENS: true
    #                 FEATURE_ASSIGN_OAUTH_TOKEN: true
    #                 BROWSER_API_CALLS_XHR_ONLY: false
    #                 REGISTRY_TITLE: Red Hat Quay
    #                 REGISTRY_TITLE_SHORT: Red Hat Quay
    #                 DATABASE_SECRET_KEY: 0ce4f796-c295-415b-bf9d-b311234704b8
    #                 SECRET_KEY: e8f9fe68-1f84-48a8-a05f-01234e6eccba
    #                 SUPER_USERS:
    #                   - quayadmin
    #                   - admin
    #                   - kemo
    #                 DISTRIBUTED_STORAGE_CONFIG:
    #                     default:
    #                         - LocalStorage
    #                         - storage_path: /datastorage/registry
    #                 DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
    #                 DISTRIBUTED_STORAGE_PREFERENCE:
    #                     - default
    #                 PREFERRED_URL_SCHEME: http
    #                 DEFAULT_TAG_EXPIRATION: 2w
    #                 TAG_EXPIRATION_OPTIONS:
    #                     - 0s
    #                     - 1d
    #                     - 1w
    #                     - 2w
    #                     - 4w
    #                     - 3y

    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          # name: quay-instance-config-secret
          name: ext-secret-quay-check
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: quayregistry-instance
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: QuayRegistry
                apiVersion: quay.redhat.com/v1
                metadata:
                  name: quay
                  namespace: quay
                spec:
                  configBundleSecret: quay-config
                  components:
                    - kind: clair
                      managed: true
                    - kind: postgres
                      managed: true
                    - kind: objectstorage
                      managed: false
                    - kind: redis
                      managed: true
                    - kind: horizontalpodautoscaler
                      managed: false
                    - kind: route
                      managed: true
                    - kind: mirror
                      managed: true
                      #overrides:
                      #  env:
                      #    - name: HTTP_PROXY
                      #      value: http://proxy.kemo.labs:3129
                      #    - name: HTTPS_PROXY
                      #      value: http://proxy.kemo.labs:3129
                      #    - name: NO_PROXY
                      #      value: '.local,.svc,localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/23,192.168.0.0/16,.kemo.network,.kemo.labs'
                    - kind: monitoring
                      managed: true
                    - kind: tls
                      managed: true
                    - kind: quay
                      managed: true
                      #overrides:
                      #  env:
                      #    - name: HTTP_PROXY
                      #      value: http://proxy.kemo.labs:3129
                      #    - name: HTTPS_PROXY
                      #      value: http://proxy.kemo.labs:3129
                      #    - name: NO_PROXY
                      #      value: '.local,.svc,localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/23,192.168.0.0/16,.kemo.network,.kemo.labs'
                    - kind: clairpostgres
                      managed: true

    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: eso-vault-clustersecretstore
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: ext-secret-quay
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: external-secrets.io/v1beta1
                kind: ExternalSecret
                metadata:
                  name: quay-config-secret
                  namespace: quay
                spec:
                  refreshInterval: "3600s"
                  secretStoreRef:
                    name: kemo-labs-vault
                    kind: ClusterSecretStore
                  target:
                    name: quay-config # name of the k8s Secret to make in this namespace
                    creationPolicy: Owner
                    deletionPolicy: Retain
                    template:
                      engineVersion: v2
                      type: Opaque # type of k8s Secret to make
                  data:
                    - secretKey: 'config.yaml' # name of the key in the k8s Secret to create
                      remoteRef:
                        key: dev.kemo/lab/tri-force/quay # name of the secret under the target Vault path
                        property: configSecretData # name of the key in that named Vault secret

    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: ext-secret-quay
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: ext-secret-quay-check
        spec:
          remediationAction: inform
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: quay-config
                  namespace: quay
                type: Opaque

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: quayregistry-route-check
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: route.openshift.io/v1
                kind: Route
                metadata:
                  namespace: quay
                  name: quay-quay
      extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: quayregistry-instance
          namespace: ""
          compliance: Compliant

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: quayregistry-consolelink
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: console.openshift.io/v1
                kind: ConsoleLink
                metadata:
                  name: quayregistry-console-link
                spec:
                  applicationMenu:
                    imageURL: 'data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDM4IDM4Ij48ZGVmcz48c3R5bGU+LnV1aWQtMjNhM2I1ZTctNzc1NC00OTQ0LWJhMjgtZWU2NWE5NjFkZGI1e2ZpbGw6I2UwMDt9LnV1aWQtYWU1ZDVlZjMtYjIwYi00MDE5LWE0ZTctZWRhY2ZhZWE0YzBme2ZpbGw6I2ZmZjt9LnV1aWQtMjI4OTNjYTEtMDk4Yi00YTJhLTlkNDUtM2NiYzViOTg2OWEwe2ZpbGw6IzRkNGQ0ZDt9PC9zdHlsZT48L2RlZnM+PGcgaWQ9InV1aWQtMTZkZjUyMDYtY2E2NC00MWRkLWI1N2UtNTVjNjYzNzBjYjk5Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iMzYiIGhlaWdodD0iMzYiIHJ4PSI5IiByeT0iOSIvPjxwYXRoIGNsYXNzPSJ1dWlkLTIyODkzY2ExLTA5OGItNGEyYS05ZDQ1LTNjYmM1Yjk4NjlhMCIgZD0ibTI4LDIuMjVjNC4yNzMzNiwwLDcuNzUsMy40NzY2NCw3Ljc1LDcuNzV2MThjMCw0LjI3MzM2LTMuNDc2NjQsNy43NS03Ljc1LDcuNzVIMTBjLTQuMjczMzYsMC03Ljc1LTMuNDc2NjQtNy43NS03Ljc1VjEwYzAtNC4yNzMzNiwzLjQ3NjY0LTcuNzUsNy43NS03Ljc1aDE4bTAtMS4yNUgxMEM1LjAyOTQ0LDEsMSw1LjAyOTQzLDEsMTB2MThjMCw0Ljk3MDU3LDQuMDI5NDQsOSw5LDloMThjNC45NzA1NiwwLDktNC4wMjk0Myw5LTlWMTBjMC00Ljk3MDU3LTQuMDI5NDQtOS05LTloMFoiLz48L2c+PGcgaWQ9InV1aWQtNzI4Njg1MGItMWY3NC00MTZjLWE5MDEtMWQ1OTAzYmU3NTkyIj48cGF0aCBjbGFzcz0idXVpZC0yM2EzYjVlNy03NzU0LTQ5NDQtYmEyOC1lZTY1YTk2MWRkYjUiIGQ9Im0xNS40OTk1MSwyOS41MjQ5Yy0uMTAzMDMsMC0uMjA3MDMtLjAyNTM5LS4zMDMyMi0uMDc4NjEtLjMwMTc2LS4xNjc0OC0uNDEwMTYtLjU0ODM0LS4yNDI2OC0uODUwMWwzLjUtNi4yOTk4Yy4xNjY5OS0uMzAxNzYuNTQ1NDEtLjQxMDY0Ljg1MDEtLjI0MjY4LjMwMTc2LjE2NzQ4LjQxMDE2LjU0ODM0LjI0MjE5Ljg1MDFsLTMuNDk5NTEsNi4yOTk4Yy0uMTE0MjYuMjA1NTctLjMyNzE1LjMyMTI5LS41NDY4OC4zMjEyOVoiLz48cGF0aCBjbGFzcz0idXVpZC1hZTVkNWVmMy1iMjBiLTQwMTktYTRlNy1lZGFjZmFlYTRjMGYiIGQ9Im0xNS41MDA0OSwyOS41MjQ5Yy0uMjE5NzMsMC0uNDMyNjItLjExNTcyLS41NDY4OC0uMzIxMjlsLTUuNS05Ljg5OTljLS4xMDQ5OC0uMTg4OTYtLjEwNDk4LS40MTg0NiwwLS42MDc0Mmw1LjUtOS44OTk5Yy4xNjg0Ni0uMzAxMjcuNTQ4ODMtLjQwOTE4Ljg1MDEtLjI0MjY4LjMwMTc2LjE2NzQ4LjQxMDE2LjU0ODM0LjI0MjY4Ljg1MDFsLTUuMzMxNTQsOS41OTYxOSw1LjMzMTU0LDkuNTk2MTljLjE2NzQ4LjMwMTc2LjA1OTA4LjY4MjYyLS4yNDI2OC44NTAxLS4wOTYxOS4wNTMyMi0uMjAwNjguMDc4NjEtLjMwMzIyLjA3ODYxWiIvPjxwYXRoIGNsYXNzPSJ1dWlkLTIzYTNiNWU3LTc3NTQtNDk0NC1iYTI4LWVlNjVhOTYxZGRiNSIgZD0ibTIyLjQ5OTAyLDI5LjUyNDljLS4xMDI1NCwwLS4yMDYwNS0uMDI1MzktLjMwMjczLS4wNzg2MS0uMzAxNzYtLjE2NzQ4LS40MTAxNi0uNTQ4MzQtLjI0MjE5LS44NTAxbDUuNS05Ljg5OTljLjE2NjAyLS4zMDE3Ni41NDU5LS40MTA2NC44NDk2MS0uMjQyNjguMzAxNzYuMTY3NDguNDEwMTYuNTQ4MzQuMjQyMTkuODUwMWwtNS41LDkuODk5OWMtLjExMzI4LjIwNTU3LS4zMjcxNS4zMjEyOS0uNTQ2ODguMzIxMjlaIi8+PHBhdGggY2xhc3M9InV1aWQtMjNhM2I1ZTctNzc1NC00OTQ0LWJhMjgtZWU2NWE5NjFkZGI1IiBkPSJtMTkuMDAwOTgsMTYuMDI0OWMtLjIyMDIxLDAtLjQzMzExLS4xMTU3Mi0uNTQ3MzYtLjMyMTI5bC0zLjUtNi4yOTk4Yy0uMTY3NDgtLjMwMTc2LS4wNTkwOC0uNjgyNjIuMjQyNjgtLjg1MDFzLjY4MjEzLS4wNTkwOC44NTAxLjI0MjY4bDMuNDk5NTEsNi4yOTk4Yy4xNjc5Ny4zMDE3Ni4wNTk1Ny42ODI2Mi0uMjQyMTkuODUwMS0uMDk2NjguMDUzMjItLjIwMDIuMDc4NjEtLjMwMjczLjA3ODYxWiIvPjxwYXRoIGNsYXNzPSJ1dWlkLWFlNWQ1ZWYzLWIyMGItNDAxOS1hNGU3LWVkYWNmYWVhNGMwZiIgZD0ibTIyLjUwMDk4LDI5LjUyNDljLS4yMTk3MywwLS40MzI2Mi0uMTE1NzItLjU0Njg4LS4zMjEyOWwtNS41MDA0OS05Ljg5OTljLS4xMDQ5OC0uMTg4OTYtLjEwNDk4LS40MTg0NiwwLS42MDc0Mmw1LjUwMDQ5LTkuODk5OWMuMTY2MDItLjMwMTc2LjU0NTktLjQxMDE2Ljg0OTYxLS4yNDI2OC4zMDE3Ni4xNjc0OC40MTAxNi41NDgzNC4yNDIxOS44NTAxbC01LjMzMTA1LDkuNTk2MTksNS4zMzEwNSw5LjU5NjE5Yy4xNjc5Ny4zMDE3Ni4wNTk1Ny42ODI2Mi0uMjQyMTkuODUwMS0uMDk2NjguMDUzMjItLjIwMDIuMDc4NjEtLjMwMjczLjA3ODYxWiIvPjxwYXRoIGNsYXNzPSJ1dWlkLTIzYTNiNWU3LTc3NTQtNDk0NC1iYTI4LWVlNjVhOTYxZGRiNSIgZD0ibTI4LjAwMDk4LDE5LjYyNWMtLjIxOTczLDAtLjQzMjYyLS4xMTU3Mi0uNTQ2ODgtLjMyMTI5bC01LjUtOS44OTk5Yy0uMTY3OTctLjMwMTc2LS4wNTk1Ny0uNjgyNjIuMjQyMTktLjg1MDEuMzAzNzEtLjE2NzQ4LjY4MTY0LS4wNTkwOC44NDk2MS4yNDI2OGw1LjUsOS44OTk5Yy4xNjc5Ny4zMDE3Ni4wNTk1Ny42ODI2Mi0uMjQyMTkuODUwMS0uMDk2NjguMDUzMjItLjIwMDIuMDc4NjEtLjMwMjczLjA3ODYxWiIvPjwvZz48L3N2Zz4='
                    section: Hub Applications
                  href: 'https://{{ (lookup "route.openshift.io/v1" "Route" "quay" "quay-quay").spec.host }}'
                  location: ApplicationMenu
                  text: Quay Container Registry
      extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: quayregistry-route-check
          namespace: ""
          compliance: Compliant