---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: instance-rhoai3
  annotations:
    policy.open-cluster-management.io/description: Deploys the Red Hat OpenShift AI Operator Instance
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2025
    policy.open-cluster-management.io/controls: OLM-INST - Operator Instance
spec:
  disabled: false
  policy-templates:
    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: Policy
          name: operators-rhoai
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rhoai-kuadrant
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: kuadrant-system
            - complianceType: musthave
              objectDefinition:
                apiVersion: kuadrant.io/v1beta1
                kind: Kuadrant
                metadata:
                  name: kuadrant
                  namespace: kuadrant-system
  
    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: Policy
          name: operators-rhoai
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rhoai-instance
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: DataScienceCluster
                apiVersion: datasciencecluster.opendatahub.io/v2
                metadata:
                  name: default-dsc
                  labels:
                    app.kubernetes.io/name: datasciencecluster
                spec:
                  components:
                    dashboard:
                      managementState: Managed
                    aipipelines:
                      managementState: Managed
                    feastoperator:
                      managementState: Managed
                    kserve:
                      managementState: Managed
                      rawDeploymentServiceConfig: Headed
                      modelsAsService:
                        managementState: Managed
                    llamastackoperator:
                      managementState: Managed
                    kueue:
                      managementState: Unmanaged
                      defaultClusterQueueName: default
                      defaultLocalQueueName: default
                    mlflowoperator:
                      managementState: Managed
                    sparkoperator:
                      managementState: Managed
                    modelregistry:
                      managementState: Managed
                      registriesNamespace: rhoai-model-registries
                    ray:
                      managementState: Managed
                    workbenches:
                      managementState: Managed
                      workbenchNamespace: rhods-notebooks
                    trainer:
                      managementState: Managed
                    trainingoperator:
                      managementState: Managed
                    trustyai:
                      managementState: Managed

    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: rhoai-operator-status
          namespace: ""
          compliance: Compliant
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: rhoai-instance
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rhoai-odhdash-check
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: opendatahub.io/v1alpha
                kind: OdhDashboardConfig
                metadata:
                  name: odh-dashboard-config
                  namespace: redhat-ods-applications

    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: rhoai-odhdash-check
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rhoai-odhdash-maas
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: opendatahub.io/v1alpha
                kind: OdhDashboardConfig
                metadata:
                  name: odh-dashboard-config
                  namespace: redhat-ods-applications
                spec:
                  dashboardConfig:
                    genAiStudio: true
                    vLLMDeploymentOnMaaS: true
