---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: instance-sandbox-containers
  annotations:
    policy.open-cluster-management.io/description: Deploys the objects needed to enable OpenShift Sandboxed Containers
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2026
    policy.open-cluster-management.io/controls: OLM-INST - Operator Instance
spec:
  disabled: false
  policy-templates:
    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: Policy
          name: operators-nfd
          namespace: ""
          compliance: Compliant
        - apiVersion: policy.open-cluster-management.io/v1
          kind: Policy
          name: instance-nfd
          namespace: ""
          compliance: Compliant
        - apiVersion: policy.open-cluster-management.io/v1
          kind: Policy
          name: operators-sandbox-containers
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: sandboxed-nfd-rule
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: nfd.openshift.io/v1alpha1
                kind: NodeFeatureRule
                metadata:
                  name: consolidated-hardware-features
                  namespace: openshift-nfd
                spec:
                  rules:
                    - name: "runtime.kata"
                      labels:
                        feature.node.kubernetes.io/runtime.kata: "true"
                      matchAny:
                        - matchFeatures:
                            - feature: cpu.cpuid
                              matchExpressions:
                                SSE42: { op: Exists }
                                VMX: { op: Exists }
                            - feature: kernel.loadedmodule
                              matchExpressions:
                                kvm: { op: Exists }
                                kvm_intel: { op: Exists }
                        - matchFeatures:
                            - feature: cpu.cpuid
                              matchExpressions:
                                SSE42: { op: Exists }
                                SVM: { op: Exists }
                            - feature: kernel.loadedmodule
                              matchExpressions:
                                kvm: { op: Exists }
                                kvm_amd: { op: Exists }
            - complianceType: musthave
              objectDefinition:
                apiVersion: nfd.openshift.io/v1alpha1
                kind: NodeFeatureRule
                metadata:
                  name: nvidia-kernel-modules
                  namespace: openshift-nfd
                spec:
                  rules:
                    - name: kernel-module-gdrdrv
                      labels:
                        nvidia.com/gdrcopy.capable: "true"
                      matchFeatures:
                        - feature: kernel.loadedmodule
                          matchExpressions:
                            gdrdrv:
                              op: Exists
                    - name: kernel-module-nvidia_fs
                      labels:
                        nvidia.com/gds.capable: "true"
                      matchFeatures:
                        - feature: kernel.loadedmodule
                          matchExpressions:
                            nvidia_fs:
                              op: Exists
                    - name: kernel-module-nvidia_peermem
                      labels:
                        nvidia.com/peermem.capable: "true"
                      matchFeatures:
                        - feature: kernel.loadedmodule
                          matchExpressions:
                            nvidia_peermem:
                              op: Exists

    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: sandboxed-nfd-rule
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: sandboxed-kataconfig
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: kataconfiguration.openshift.io/v1
                kind: KataConfig
                metadata:
                  name: sandboxed-kataconfig
                spec:
                  checkNodeEligibility: false
                  enablePeerPods: false
                  kataConfigPoolSelector:
                    matchExpressions:
                      - key: feature.node.kubernetes.io/runtime.kata
                        operator: Exists
                  logLevel: info

    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: sandboxed-kataconfig
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: sandboxed-runtime-check
        spec:
          remediationAction: inform
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: node.k8s.io/v1
                kind: RuntimeClass
                metadata:
                  name: kata

    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: nvidia-gpu-operator-status
          namespace: ""
          compliance: Compliant
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: sandboxed-runtime-check
          namespace: ""
          compliance: Compliant
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: nvidia-gpu-instance
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: nvidia-gpu-kata
        spec:
          remediationAction: enforce
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: nvidia.com/v1
                kind: ClusterPolicy
                metadata:
                  name: gpu-cluster-policy
                spec:
                  kataSandboxDevicePlugin:
                    enabled: true
                    env:
                      - name: P_GPU_ALIAS
                        value: pgpu
                      - name: NVSWITCH_ALIAS
                        value: nvswitch
                  vfioManager:
                    enabled: true
                    env:
                      - name: BIND_NVSWITCHES
                        value: 'true'