---
kind: L2Advertisement
apiVersion: metallb.io/v1beta1
metadata:
  name: v60-general-pools
  namespace: metallb-system
spec:
  ipAddressPools:
    - v60-auto-pool
    - v60-high-pool
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: v60-auto-pool
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  addresses:
    - 192.168.60.20-192.168.60.30
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: v60-high-pool
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  addresses:
    - 192.168.60.110-192.168.60.150
  autoAssign: false