---
kind: L2Advertisement
apiVersion: metallb.io/v1beta1
metadata:
  name: hcp-pools
  namespace: metallb-system
spec:
  ipAddressPools:
    - v60-hcp-virt-api
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: v60-hcp-virt-api
  namespace: metallb-system
spec:
  addresses:
    - 192.168.60.100/32
    - 192.168.60.101/32
    - 192.168.60.102/32
    - 192.168.60.103/32
    - 192.168.60.104/32
    - 192.168.60.105/32
    - 192.168.60.106/32
  autoAssign: true
  avoidBuggyIPs: true
  serviceAllocation:
    priority: 50
    serviceSelectors:
      - matchExpressions:
          - {key: 'hypershift.openshift.io/control-plane-component', operator: In, values: ['kube-apiserver']}