# This NAD uses a VLAN defined in a router but is otherwise non-routed and has no default networking.
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: nad-live-migrate
  namespace: openshift-cnv
spec:
  config: |-
    {
        "cniVersion": "0.4.0",
        "name": "vmnet",
        "type": "ovn-k8s-cni-overlay",
        "netAttachDefName": "openshift-cnv/nad-live-migrate",
        "topology": "localnet",
        "vlanID": 530,
        "mtu": 9000,
        "subnets": "192.168.53.0/24"
    }
