---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: baremetal-network
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "0.3.1", 
      "type": "ovn-k8s-cni-overlay", 
      "topology": "localnet",
      "name": "baremetal-network", 
      "netAttachDefName": "default/baremetal-network",
      "mtu": 9000
    }