apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vlan420
spec:
  # nodeSelector:
  #   kubernetes.io/hostname: raza
  desiredState:
    interfaces:
      - description: VLAN 420 using bond0
        ipv4:
          dhcp: false
          enabled: false
        # mtu: 9000
        name: bond0.420
        state: up
        type: vlan
        vlan:
          base-iface: bond0
          id: 420
      - bridge:
          options:
            stp:
              enabled: false
          port:
            - name: bond0.420
        description: Linux bridge with bond0 VLAN 420 as a port, used for MetalLB
        # mtu: 9000
        name: br420
        state: up
        type: linux-bridge