---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  annotations:
    cluster.open-cluster-management.io/submariner-broker-ns: aws-self-managed-broker
  name: aws-self-managed
spec:
  clusterSelector:
    selectorType: ExclusiveClusterSetLabel
