FROM registry.fedoraproject.org/fedora:44

ARG USER_HOME_DIR="/projects"

ENV HOME=${USER_HOME_DIR}

RUN dnf -y update && dnf -y install dnf-plugins-core crun \
    && dnf config-manager addrepo --from-repofile https://download.docker.com/linux/fedora/docker-ce.repo \
    && dnf install -y docker-ce-3:29.8.2-1.fc44 docker-ce-cli-1:29.8.2-1.fc44 docker-ce-rootless-extras-0:29.8.2-1.fc44 containerd.io docker-buildx-plugin docker-compose-plugin \
    && dnf install -y iproute shadow-utils fuse-overlayfs slirp4netns sudo wget git erofs-utils qemu-user-static bash overlayfs-tools iptables-nft procps-ng \
    && dnf clean all

RUN set -eux; \
	\
	apkArch="$(uname -m)"; \
	case "$apkArch" in \
		'x86_64') \
			url='https://download.docker.com/linux/static/stable/x86_64/docker-29.8.2.tgz'; \
			;; \
		'armhf') \
			url='https://download.docker.com/linux/static/stable/armel/docker-29.8.2.tgz'; \
			;; \
		'armv7') \
			url='https://download.docker.com/linux/static/stable/armhf/docker-29.8.2.tgz'; \
			;; \
		'aarch64') \
			url='https://download.docker.com/linux/static/stable/aarch64/docker-29.8.2.tgz'; \
			;; \
		*) echo >&2 "error: unsupported 'docker.tgz' architecture ($apkArch)"; exit 1 ;; \
	esac; \
	\
	wget -O 'docker.tgz' "$url"; \
	\
	tar --extract \
		--file docker.tgz \
		--strip-components 1 \
		--directory /usr/local/bin/ \
		--no-same-owner \
# we exclude the CLI binary because we already extracted that over in the "docker:29-cli" image that we're FROM and we don't want to duplicate those bytes again in this layer
		--exclude 'docker/docker' \
		--exclude 'docker/runc' \
		--exclude 'docker/dockerd' \
		--exclude 'docker/ctr' \
		--exclude 'docker/containerd-shim-runc-v2' \
	; \
	rm docker.tgz;

RUN set -eux; \
	\
	apkArch="$(uname -m)"; \
	case "$apkArch" in \
		'x86_64') \
			url='https://github.com/moby/buildkit/releases/download/v0.34.0/buildkit-v0.34.0.linux-amd64.tar.gz'; \
			;; \
		'armv7') \
			url='https://github.com/moby/buildkit/releases/download/v0.34.0/buildkit-v0.34.0.linux-arm-v7.tar.gz'; \
			;; \
		'aarch64') \
			url='https://github.com/moby/buildkit/releases/download/v0.34.0/buildkit-v0.34.0.linux-arm64.tar.gz'; \
			;; \
		*) echo >&2 "error: unsupported 'docker.tgz' architecture ($apkArch)"; exit 1 ;; \
	esac; \
	\
	wget -O 'buildkit.tgz' "$url"; \
	\
	tar --extract \
		--file buildkit.tgz \
		--strip-components 1 \
		--directory /usr/local/bin/ \
		--no-same-owner \
	; \
	rm buildkit.tgz;

# set up subuid/subgid so that "--userns-remap=default" works out-of-the-box
RUN set -eux; \
	groupadd -r dockremap; \
	useradd -r -g dockremap dockremap; \
	echo 'dockremap:165536:65536' >> /etc/subuid; \
	echo 'dockremap:165536:65536' >> /etc/subgid

RUN \
    ##
    ## Setup for root-less podman
    ##
    #
    # Add the user to /etc/passwd and /etc/group
    # Add the user with the UID that the SCC will enforce
    groupadd -g 1000 user ; \
    useradd -u 1000 -g 1000 -d ${USER_HOME_DIR} -s /bin/bash user  ; \
    usermod -L user  ; \
    usermod -aG docker user ; \
    chmod 400 /etc/shadow  ; \
    chown -R 1000:1000 ${USER_HOME_DIR} ; \
    #
    # Enable podman to create uid and gid maps for the user
    chown root:user /etc/subuid /etc/subgid ; \
    chmod 664 /etc/subuid /etc/subgid ; \
    setcap cap_setuid+ep /usr/bin/newuidmap ; \
    setcap cap_setgid+ep /usr/bin/newgidmap ; \
    echo "user ALL=NOPASSWD: /setup-cgroups.sh" >> /etc/sudoers

COPY daemon.json /etc/docker/daemon.json
COPY dind /usr/local/bin/dind
COPY --chown=0:0 setup-cgroups.sh /
COPY dockerd-entrypoint.sh /usr/local/bin/dockerd-entrypoint.sh
RUN chmod +x /usr/local/bin/dind \
    && chmod +x /usr/local/bin/dockerd-entrypoint.sh \
    && chmod +x /setup-cgroups.sh \
    && wget -O /usr/local/bin/ocp https://raw.githubusercontent.com/lmcclint/ocp-version-manager/refs/heads/main/ocp \
    && chmod a+x /usr/local/bin/ocp \
    && OCP_BIN_DIR=/usr/local/bin ocp get stable-4.22 \
    && OCP_BIN_DIR=/usr/local/bin ocp use stable-4.22

VOLUME /var/lib/docker
EXPOSE 2375 2376

# ENV DOCKERD_ROOTLESS_ROOTLESSKIT_NET=slirp4netns

# # The SCC that we are using will ensure that the user runs as UID 1000 in its own user namespace on the host node.
# USER 1000
# WORKDIR ${USER_HOME_DIR}
# RUN dockerd-rootless-setuptool.sh install

ENTRYPOINT ["dockerd-entrypoint.sh"]
CMD []