---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-policies

resources:
  - move-to-infra/

  - aws-infra-machinesets.yaml
  - aws-odf-machinesets.yaml
  - aws-nvidia-machinesets.yaml

  - azure-infra-machinesets.yaml
  - azure-odf-machinesets.yaml
  - azure-nvidia-machinesets.yaml

  - machineconfigpool-infra.yaml
  - machineconfigpool-storage.yaml
  - machineconfigpool-gpu.yaml

  - vsphere-infra-machinesets.yaml