---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-rbac
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/kenmoini/lab-ocp'
      targetRevision: main
      path: configuration/rbac/groups/
      kustomize: {}

  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    automated:
      prune: false
      allowEmpty: true
      selfHeal: true # overrides changes made on the cluster that drift from git state
    retry:
      limit: 2