apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    cluster.ocs.openshift.io/local-devices: 'true'
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  storageDeviceSets:
    - deviceClass: ssd
      count: 5
      replica: 3
      dataPVCTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: '1'
          storageClassName: lso-odf
          volumeMode: Block
      name: ocs-deviceset-lso-odf
      placement: {}
      portable: false
      resources: {}
  encryption:
    clusterWide: false
    enable: false
    kms:
      enable: false
    storageClass: false
  monDataDirHostPath: /var/lib/rook
  managedResources:
    cephBlockPools:
      defaultStorageClass: true
      defaultVirtualizationStorageClass: true
  arbiter: {}
  # manageNodes: false
  network:
    connections:
      encryption: {}
    provider: multus
    multiClusterService: {}
    selectors:
      cluster: openshift-storage/cluster-net
      public: openshift-storage/public-net
  nodeTopologies: {}
  externalStorage: {}
  resourceProfile: lean
  # flexibleScaling: true
