---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: quay-oauth-secret
  # namespace: quay
  annotations:
    policy.open-cluster-management.io/description: Provides OAuthClient secret injection for Quay
    policy.open-cluster-management.io/categories: OCPOM - OpenShift Operator Management
    policy.open-cluster-management.io/standards: Kemo Labs 2026
    policy.open-cluster-management.io/controls: OLM-INST - Operator Instance
spec:
  disabled: false
  policy-templates:
    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: eso-vault-clustersecretstore
          namespace: ""
          compliance: Compliant
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: ext-secret-quay-check
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: eso-quay-oauth
        spec:
          remediationAction: enforce
          severity: critical
          pruneObjectBehavior: DeleteIfCreated
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: external-secrets.io/v1beta1
                kind: ExternalSecret
                metadata:
                  name: quay-oauth-secret
                  namespace: quay
                spec:
                  refreshInterval: "3600s"
                  secretStoreRef:
                    name: kemo-labs-vault
                    kind: ClusterSecretStore
                  target:
                    name: quay-oauth-secret # name of the k8s Secret to make in this namespace
                    creationPolicy: Owner
                    deletionPolicy: Retain
                    template:
                      engineVersion: v2
                      type: Opaque # type of k8s Secret to make
                  data:
                    - secretKey: 'clientSecret' # name of the key in the k8s Secret to create
                      remoteRef:
                        key: dev.kemo/lab/tri-force/quay # name of the secret under the target Vault path
                        property: oauthClientSecret # name of the key in that named Vault secret

    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: eso-quay-oauth
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: eso-quay-oauth-check
        spec:
          remediationAction: inform
          severity: critical
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: quay-oauth-secret
                  namespace: quay
                type: Opaque

    - extraDependencies:
        - apiVersion: policy.open-cluster-management.io/v1
          kind: ConfigurationPolicy
          name: eso-quay-oauth-check
          namespace: ""
          compliance: Compliant
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: quay-oauth-client
        spec:
          remediationAction: enforce
          severity: critical
          pruneObjectBehavior: DeleteIfCreated
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: oauth.openshift.io/v1
                kind: OAuthClient
                metadata:
                  name: quay
                secret: '{{ fromSecret "quay" "quay-oauth-secret" "clientSecret" | base64dec }}'
                redirectURIs:
                  - 'https://{{ (lookup "route.openshift.io/v1" "Route" "quay" "quay-quay").spec.host }}/oauth2/callback'
                grantMethod: auto
