---
apiVersion: forklift.konveyor.io/v1beta1
kind: Provider
metadata:
  name: kemo-labs-vcenter
  namespace: openshift-mtv
spec:
  secret:
    name: kemo-labs-vcenter
    namespace: openshift-mtv
  settings:
    sdkEndpoint: vcenter
    vddkInitImage: 'disconn-harbor.d70.kemo.labs/library/vddk:latest'
  type: vsphere
  url: 'https://vcenter.kemo.labs/sdk'